-- ============================================================================
-- 120_complaint_master_patient_language.sql
-- subjective-tab · Phase 2 follow-up
-- Date: 2026-06-06
-- ============================================================================
-- Reworks the complaint_master seed (117) to PATIENT LANGUAGE only.
--
-- Chief complaints are how a patient describes their problem in their own
-- words ("Stomach pain", "Loose stools", "Fever with shivering") — never the
-- doctor's clinical label or a diagnosis. This migration:
--   1. Renames clinical names to lay terms; the old medical word is preserved
--      as a *synonym* so search still resolves it (synonyms are search-only and
--      no longer displayed in the dropdown — see ComplaintAutocomplete).
--   2. Removes pure diagnoses (Tension/Cluster headache, Sciatica, FUO,
--      Whooping cough, Dengue/Typhoid-like fever, etc.) — these are not
--      chief complaints.
--   3. Merges duplicates (Diarrhea→Loose stools, Edema→Swelling,
--      Abdominal distension→Bloating, Nasal congestion→Blocked nose,
--      Breath odor→Bad breath, Cough with sputum→Cough with phlegm).
--   4. Adds high-frequency patient complaints that were missing
--      (Period pain, Cold, Acidity, Wheezing, Loss of smell/taste, etc.).
--
-- This file is now the single source of truth for the seed; it fully replaces
-- the rows seeded by 117. Idempotent: re-running refreshes the table.
-- No FKs reference complaint_master.id (complaints store name + category as
-- text), so a clean re-seed is safe.
-- Rollback: re-run 117's seed block.
-- ============================================================================

DELETE FROM complaint_master;

INSERT INTO complaint_master (name, synonyms, category)
SELECT v.name, v.synonyms, v.category
FROM (VALUES
  -- ---------- PAIN ----------
  ('Headache', '{cephalgia}'::text[], 'pain'),
  ('Migraine', '{}'::text[], 'pain'),
  ('Back pain', '{}'::text[], 'pain'),
  ('Lower back pain', '{lumbago,LBA}'::text[], 'pain'),
  ('Upper back pain', '{}'::text[], 'pain'),
  ('Neck pain', '{}'::text[], 'pain'),
  ('Shoulder pain', '{}'::text[], 'pain'),
  ('Knee pain', '{}'::text[], 'pain'),
  ('Hip pain', '{}'::text[], 'pain'),
  ('Ankle pain', '{}'::text[], 'pain'),
  ('Foot pain', '{}'::text[], 'pain'),
  ('Heel pain', '{plantar fasciitis}'::text[], 'pain'),
  ('Leg pain', '{}'::text[], 'pain'),
  ('Arm pain', '{}'::text[], 'pain'),
  ('Elbow pain', '{}'::text[], 'pain'),
  ('Wrist pain', '{}'::text[], 'pain'),
  ('Hand pain', '{}'::text[], 'pain'),
  ('Finger pain', '{}'::text[], 'pain'),
  ('Chest pain', '{}'::text[], 'pain'),
  ('Stomach pain', '{abdominal pain,stomach ache,tummy pain}'::text[], 'pain'),
  ('Upper stomach pain', '{epigastric pain}'::text[], 'pain'),
  ('Lower tummy pain', '{pelvic pain}'::text[], 'pain'),
  ('Side pain', '{flank pain}'::text[], 'pain'),
  ('Joint pain', '{arthralgia}'::text[], 'pain'),
  ('Muscle pain', '{myalgia}'::text[], 'pain'),
  ('Body ache', '{body pain}'::text[], 'pain'),
  ('Toothache', '{tooth pain}'::text[], 'pain'),
  ('Ear pain', '{otalgia,earache}'::text[], 'pain'),
  ('Eye pain', '{}'::text[], 'pain'),
  ('Throat pain', '{}'::text[], 'pain'),
  ('Testicular pain', '{}'::text[], 'pain'),
  ('Breast pain', '{}'::text[], 'pain'),
  ('Bone pain', '{}'::text[], 'pain'),
  ('Facial pain', '{}'::text[], 'pain'),
  ('Jaw pain', '{TMJ pain,jaw joint pain}'::text[], 'pain'),
  ('Groin pain', '{}'::text[], 'pain'),
  ('Calf pain', '{}'::text[], 'pain'),
  ('Period pain', '{menstrual cramps,period cramps,dysmenorrhea}'::text[], 'pain'),
  -- ---------- FEVER ----------
  ('Fever', '{pyrexia}'::text[], 'fever'),
  ('High fever', '{high-grade fever}'::text[], 'fever'),
  ('Mild fever', '{low-grade fever}'::text[], 'fever'),
  ('Fever with chills', '{}'::text[], 'fever'),
  ('Fever with shivering', '{fever with rigors,rigors}'::text[], 'fever'),
  ('Fever that comes and goes', '{intermittent fever}'::text[], 'fever'),
  ('Continuous fever', '{}'::text[], 'fever'),
  ('Fever after vaccination', '{post-vaccination fever}'::text[], 'fever'),
  ('Night sweats with fever', '{}'::text[], 'fever'),
  ('Fever with rash', '{}'::text[], 'fever'),
  ('Repeated fever', '{recurrent fever}'::text[], 'fever'),
  -- ---------- COUGH / NOSE / THROAT ----------
  ('Cough', '{}'::text[], 'cough'),
  ('Dry cough', '{}'::text[], 'cough'),
  ('Cough with phlegm', '{productive cough,cough with sputum,sputum}'::text[], 'cough'),
  ('Cough with blood', '{hemoptysis}'::text[], 'cough'),
  ('Long-standing cough', '{chronic cough}'::text[], 'cough'),
  ('Recent cough', '{acute cough}'::text[], 'cough'),
  ('Night cough', '{}'::text[], 'cough'),
  ('Morning cough', '{}'::text[], 'cough'),
  ('Barking cough', '{}'::text[], 'cough'),
  ('Cough with wheeze', '{}'::text[], 'cough'),
  ('Mucus dripping in throat', '{post-nasal drip}'::text[], 'cough'),
  ('Sore throat', '{pharyngitis,throat irritation}'::text[], 'cough'),
  ('Hoarse voice', '{hoarseness}'::text[], 'cough'),
  ('Blocked nose', '{stuffy nose,nasal congestion,nasal blockage}'::text[], 'cough'),
  ('Runny nose', '{rhinorrhea}'::text[], 'cough'),
  ('Sneezing', '{}'::text[], 'cough'),
  ('Cold and cough', '{}'::text[], 'cough'),
  ('Cold', '{common cold,head cold}'::text[], 'cough'),
  -- ---------- GENERAL ----------
  ('Nausea', '{}'::text[], 'default'),
  ('Vomiting', '{emesis}'::text[], 'default'),
  ('Loose stools', '{diarrhea,loose motions}'::text[], 'default'),
  ('Constipation', '{}'::text[], 'default'),
  ('Bloating', '{abdominal distension,bloated tummy,gas}'::text[], 'default'),
  ('Loss of appetite', '{anorexia}'::text[], 'default'),
  ('Weight loss', '{}'::text[], 'default'),
  ('Weight gain', '{}'::text[], 'default'),
  ('Tiredness', '{fatigue}'::text[], 'default'),
  ('Weakness', '{generalized weakness}'::text[], 'default'),
  ('Feeling unwell', '{malaise}'::text[], 'default'),
  ('Dizziness', '{giddiness}'::text[], 'default'),
  ('Spinning sensation', '{vertigo}'::text[], 'default'),
  ('Heart racing', '{palpitations,heart pounding}'::text[], 'default'),
  ('Shortness of breath', '{breathlessness,SOB}'::text[], 'default'),
  ('Chest tightness', '{}'::text[], 'default'),
  ('Swelling', '{edema}'::text[], 'default'),
  ('Rash', '{}'::text[], 'default'),
  ('Itching', '{pruritus}'::text[], 'default'),
  ('Hives', '{urticaria}'::text[], 'default'),
  ('Acne', '{pimples}'::text[], 'default'),
  ('Hair fall', '{alopecia}'::text[], 'default'),
  ('Difficulty sleeping', '{insomnia,sleeplessness}'::text[], 'default'),
  ('Anxiety', '{}'::text[], 'default'),
  ('Feeling low', '{depressed mood,low mood}'::text[], 'default'),
  ('Burning urination', '{dysuria}'::text[], 'default'),
  ('Frequent urination', '{increased urination,polyuria}'::text[], 'default'),
  ('Decreased urination', '{oliguria}'::text[], 'default'),
  ('Sudden urge to urinate', '{urinary urgency}'::text[], 'default'),
  ('Urine leakage', '{urinary incontinence}'::text[], 'default'),
  ('Blood in urine', '{hematuria}'::text[], 'default'),
  ('Vaginal discharge', '{}'::text[], 'default'),
  ('White discharge', '{leucorrhea}'::text[], 'default'),
  ('Irregular periods', '{}'::text[], 'default'),
  ('Heavy periods', '{menorrhagia}'::text[], 'default'),
  ('Missed periods', '{amenorrhea}'::text[], 'default'),
  ('Erectile dysfunction', '{}'::text[], 'default'),
  ('Low sex drive', '{decreased libido}'::text[], 'default'),
  ('Hearing loss', '{}'::text[], 'default'),
  ('Ringing in ears', '{tinnitus}'::text[], 'default'),
  ('Blurred vision', '{visual blurring}'::text[], 'default'),
  ('Double vision', '{diplopia}'::text[], 'default'),
  ('Red eye', '{}'::text[], 'default'),
  ('Watering eye', '{epiphora}'::text[], 'default'),
  ('Numbness', '{}'::text[], 'default'),
  ('Tingling', '{paresthesia}'::text[], 'default'),
  ('Shaking or trembling', '{tremors}'::text[], 'default'),
  ('Fits', '{convulsions,seizures}'::text[], 'default'),
  ('Confusion', '{}'::text[], 'default'),
  ('Memory loss', '{}'::text[], 'default'),
  ('Difficulty swallowing', '{dysphagia}'::text[], 'default'),
  ('Heartburn', '{}'::text[], 'default'),
  ('Acid reflux', '{GERD}'::text[], 'default'),
  ('Acidity', '{hyperacidity}'::text[], 'default'),
  ('Burping', '{belching}'::text[], 'default'),
  ('Excessive thirst', '{polydipsia}'::text[], 'default'),
  ('Excessive hunger', '{polyphagia}'::text[], 'default'),
  ('Cannot tolerate cold', '{cold intolerance}'::text[], 'default'),
  ('Cannot tolerate heat', '{heat intolerance}'::text[], 'default'),
  ('Excessive sweating', '{hyperhidrosis}'::text[], 'default'),
  ('Looking pale', '{pallor}'::text[], 'default'),
  ('Easy bruising', '{}'::text[], 'default'),
  ('Bleeding gums', '{}'::text[], 'default'),
  ('Mouth ulcer', '{}'::text[], 'default'),
  ('Dry mouth', '{xerostomia}'::text[], 'default'),
  ('Bad breath', '{halitosis,breath odor}'::text[], 'default'),
  ('Limp', '{}'::text[], 'default'),
  ('Difficulty walking', '{}'::text[], 'default'),
  ('Stiffness', '{}'::text[], 'default'),
  ('Difficulty moving', '{reduced mobility}'::text[], 'default'),
  ('Wound', '{}'::text[], 'default'),
  ('Burn', '{}'::text[], 'default'),
  ('Insect bite', '{}'::text[], 'default'),
  ('Allergic reaction', '{}'::text[], 'default'),
  ('Skin allergy', '{skin rash allergy}'::text[], 'default'),
  ('Boil', '{abscess}'::text[], 'default'),
  ('Feeling of something stuck', '{foreign body sensation}'::text[], 'default'),
  ('Something in eye', '{foreign body in eye}'::text[], 'default'),
  ('Something in ear', '{foreign body in ear}'::text[], 'default'),
  ('Motion sickness', '{}'::text[], 'default'),
  ('Hiccups', '{}'::text[], 'default'),
  ('Snoring', '{}'::text[], 'default'),
  ('Bedwetting', '{enuresis}'::text[], 'default'),
  ('Daytime sleepiness', '{}'::text[], 'default'),
  ('Loss of consciousness', '{syncope}'::text[], 'default'),
  ('Fainting', '{}'::text[], 'default'),
  ('Bleeding from back passage', '{bleeding per rectum,blood in stool}'::text[], 'default'),
  ('Black stools', '{melena}'::text[], 'default'),
  ('Piles', '{hemorrhoids}'::text[], 'default'),
  ('Pain in back passage', '{anal pain}'::text[], 'default'),
  ('Gas trouble', '{flatulence}'::text[], 'default'),
  ('Indigestion', '{dyspepsia}'::text[], 'default'),
  ('Food poisoning', '{}'::text[], 'default'),
  ('Dehydration', '{}'::text[], 'default'),
  ('Heat exhaustion', '{}'::text[], 'default'),
  ('Sunburn', '{}'::text[], 'default'),
  ('Dry skin', '{}'::text[], 'default'),
  ('Oily skin', '{}'::text[], 'default'),
  ('Dark patches on skin', '{pigmentation}'::text[], 'default'),
  ('Dark circles', '{}'::text[], 'default'),
  ('Excessive hair growth', '{hirsutism}'::text[], 'default'),
  ('Chest discomfort', '{}'::text[], 'default'),
  ('Leg cramps', '{}'::text[], 'default'),
  ('Restless legs', '{}'::text[], 'default'),
  ('Loss of smell', '{anosmia}'::text[], 'default'),
  ('Loss of taste', '{ageusia}'::text[], 'default'),
  ('Wheezing', '{wheeze}'::text[], 'default'),
  ('Yellowing of eyes or skin', '{jaundice}'::text[], 'default'),
  ('Snake bite', '{}'::text[], 'default'),
  ('Dog bite', '{}'::text[], 'default'),
  ('Accident injury', '{road traffic accident,RTA}'::text[], 'default'),
  ('Fall injury', '{}'::text[], 'default')
) AS v(name, synonyms, category)
WHERE NOT EXISTS (
  SELECT 1 FROM complaint_master c WHERE lower(c.name) = lower(v.name)
);
