-- ============================================================================
-- 214_doctor_settings_letterhead_tokens.sql
-- clinic-branding — page margins, logo size, patient block, footer line.
-- Date:    2026-08-25
-- ============================================================================
-- Purpose:
--   Additive letterhead tokens on doctor_settings. No layout builder.
--   Registration number is still not a column (BRD-D2).
--
-- Safety:
--   · Additive only.
--   · ADD COLUMN IF NOT EXISTS + DROP/ADD CONSTRAINT pairs are idempotent.
--   · Reverse migration documented at the file foot.
-- ============================================================================

ALTER TABLE doctor_settings
  ADD COLUMN IF NOT EXISTS page_margin_top_mm INTEGER NOT NULL DEFAULT 12;

ALTER TABLE doctor_settings
  ADD COLUMN IF NOT EXISTS page_margin_right_mm INTEGER NOT NULL DEFAULT 12;

ALTER TABLE doctor_settings
  ADD COLUMN IF NOT EXISTS page_margin_bottom_mm INTEGER NOT NULL DEFAULT 12;

ALTER TABLE doctor_settings
  ADD COLUMN IF NOT EXISTS page_margin_left_mm INTEGER NOT NULL DEFAULT 12;

ALTER TABLE doctor_settings
  ADD COLUMN IF NOT EXISTS logo_size TEXT NOT NULL DEFAULT 'medium';

ALTER TABLE doctor_settings
  ADD COLUMN IF NOT EXISTS patient_identity_preset TEXT NOT NULL DEFAULT 'open_letter';

ALTER TABLE doctor_settings
  ADD COLUMN IF NOT EXISTS show_patient_phone BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE doctor_settings
  ADD COLUMN IF NOT EXISTS show_patient_guardian BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE doctor_settings
  ADD COLUMN IF NOT EXISTS show_patient_mrn BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE doctor_settings
  ADD COLUMN IF NOT EXISTS show_patient_address BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE doctor_settings
  ADD COLUMN IF NOT EXISTS letterhead_footer_line TEXT NULL;

ALTER TABLE doctor_settings
  ADD COLUMN IF NOT EXISTS hide_halo_credit BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE doctor_settings
  DROP CONSTRAINT IF EXISTS doctor_settings_page_margin_top_mm_check;
ALTER TABLE doctor_settings
  ADD CONSTRAINT doctor_settings_page_margin_top_mm_check
  CHECK (page_margin_top_mm >= 8 AND page_margin_top_mm <= 32);

ALTER TABLE doctor_settings
  DROP CONSTRAINT IF EXISTS doctor_settings_page_margin_right_mm_check;
ALTER TABLE doctor_settings
  ADD CONSTRAINT doctor_settings_page_margin_right_mm_check
  CHECK (page_margin_right_mm >= 8 AND page_margin_right_mm <= 32);

ALTER TABLE doctor_settings
  DROP CONSTRAINT IF EXISTS doctor_settings_page_margin_bottom_mm_check;
ALTER TABLE doctor_settings
  ADD CONSTRAINT doctor_settings_page_margin_bottom_mm_check
  CHECK (page_margin_bottom_mm >= 8 AND page_margin_bottom_mm <= 32);

ALTER TABLE doctor_settings
  DROP CONSTRAINT IF EXISTS doctor_settings_page_margin_left_mm_check;
ALTER TABLE doctor_settings
  ADD CONSTRAINT doctor_settings_page_margin_left_mm_check
  CHECK (page_margin_left_mm >= 8 AND page_margin_left_mm <= 32);

ALTER TABLE doctor_settings
  DROP CONSTRAINT IF EXISTS doctor_settings_logo_size_check;
ALTER TABLE doctor_settings
  ADD CONSTRAINT doctor_settings_logo_size_check
  CHECK (logo_size IN ('small', 'medium', 'large'));

ALTER TABLE doctor_settings
  DROP CONSTRAINT IF EXISTS doctor_settings_patient_identity_preset_check;
ALTER TABLE doctor_settings
  ADD CONSTRAINT doctor_settings_patient_identity_preset_check
  CHECK (patient_identity_preset IN ('open_letter', 'compact', 'minimal'));

ALTER TABLE doctor_settings
  DROP CONSTRAINT IF EXISTS doctor_settings_letterhead_footer_line_check;
ALTER TABLE doctor_settings
  ADD CONSTRAINT doctor_settings_letterhead_footer_line_check
  CHECK (letterhead_footer_line IS NULL OR char_length(letterhead_footer_line) <= 200);

COMMENT ON COLUMN doctor_settings.page_margin_top_mm IS
  'clinic-branding tokens. Body page margin in mm for non-preprinted presets (8–32).';
COMMENT ON COLUMN doctor_settings.logo_size IS
  'clinic-branding tokens. small | medium | large logo on classic/centred.';
COMMENT ON COLUMN doctor_settings.patient_identity_preset IS
  'clinic-branding tokens. open_letter | compact | minimal patient block.';
COMMENT ON COLUMN doctor_settings.letterhead_footer_line IS
  'clinic-branding tokens. Optional clinic phone/hours line. Never a patient phone.';
COMMENT ON COLUMN doctor_settings.hide_halo_credit IS
  'clinic-branding tokens. When true, omit the Generated by Halo Aid line.';

-- ============================================================================
-- Reverse migration (manual):
--
--   ALTER TABLE doctor_settings
--     DROP CONSTRAINT IF EXISTS doctor_settings_letterhead_footer_line_check;
--   ALTER TABLE doctor_settings
--     DROP CONSTRAINT IF EXISTS doctor_settings_patient_identity_preset_check;
--   ALTER TABLE doctor_settings
--     DROP CONSTRAINT IF EXISTS doctor_settings_logo_size_check;
--   ALTER TABLE doctor_settings
--     DROP CONSTRAINT IF EXISTS doctor_settings_page_margin_left_mm_check;
--   ALTER TABLE doctor_settings
--     DROP CONSTRAINT IF EXISTS doctor_settings_page_margin_bottom_mm_check;
--   ALTER TABLE doctor_settings
--     DROP CONSTRAINT IF EXISTS doctor_settings_page_margin_right_mm_check;
--   ALTER TABLE doctor_settings
--     DROP CONSTRAINT IF EXISTS doctor_settings_page_margin_top_mm_check;
--   ALTER TABLE doctor_settings DROP COLUMN IF EXISTS hide_halo_credit;
--   ALTER TABLE doctor_settings DROP COLUMN IF EXISTS letterhead_footer_line;
--   ALTER TABLE doctor_settings DROP COLUMN IF EXISTS show_patient_address;
--   ALTER TABLE doctor_settings DROP COLUMN IF EXISTS show_patient_mrn;
--   ALTER TABLE doctor_settings DROP COLUMN IF EXISTS show_patient_guardian;
--   ALTER TABLE doctor_settings DROP COLUMN IF EXISTS show_patient_phone;
--   ALTER TABLE doctor_settings DROP COLUMN IF EXISTS patient_identity_preset;
--   ALTER TABLE doctor_settings DROP COLUMN IF EXISTS logo_size;
--   ALTER TABLE doctor_settings DROP COLUMN IF EXISTS page_margin_left_mm;
--   ALTER TABLE doctor_settings DROP COLUMN IF EXISTS page_margin_bottom_mm;
--   ALTER TABLE doctor_settings DROP COLUMN IF EXISTS page_margin_right_mm;
--   ALTER TABLE doctor_settings DROP COLUMN IF EXISTS page_margin_top_mm;
-- ============================================================================
