-- ============================================================================
-- Drug Master seed: India FDC + programme expand + catalog cleanup
-- ============================================================================
-- Migration: 230_drug_master_seed_expand_combos.sql
-- Date:      2026-09-09
-- Description:
--   1. Cleanup brand-as-generic names (Avil, Deriphyllin, Buscopan,
--      Candibiotic, Wax softener) and non-INN labels (Combined Oral
--      Contraceptive, Antacid).
--   2. Drop true-duplicate qualifier rows (same molecule + form + strength).
--   3. Strip route/site parentheticals from generic_name — form and
--      route_default already carry that (so the capture bar can show
--      "Drops Ofloxacin 0.3%" instead of "Drops Ofloxacin (eye) 0.3%").
--      Insulin / vitamin INN parentheticals are kept.
--   4. Insert India-OPD combination products plus national-programme
--      (NTEP, NVBDCP, Anaemia Mukt Bharat) and endemic-region singles.
--
--   Brand names stay populated as a hidden search + allergy-match key.
--   They are not shown in the capture-bar dropdown.
--
--   Omitted pending clinical review (CDSCO / rationality contested):
--     cephalosporin+FQ or cephalosporin+clavulanate FDCs, Nimesulide +
--     Paracetamol, triple NSAID/relaxant, four-drug cough syrups,
--     steroid-antifungal derm combos, HQ+tretinoin+steroid triples,
--     aspirin+statin+P2Y12 polypills.
--
--   Generated by: backend/scripts/generate-drug-master-seed-combos.js
--   Insert rows in this file: 142
--
--   Idempotent:
--     DELETE / UPDATE match the pre-cleanup generic_name (no-op after apply).
--     INSERT is guarded on lower(generic_name) + form + strength so the
--     same INN can exist as tablet and drops.
-- ============================================================================

-- 1. Drop true duplicates (FK: prescription_medicines SET NULL,
--    drug_interactions / doctor_drug_usage CASCADE).
DELETE FROM drug_master
WHERE generic_name IN ('Rifaximin (hepatic)', 'Baclofen (neuro)', 'Hydroxychloroquine (rheum)', 'Sulfasalazine (rheum)', 'Sodium Bicarbonate (alkaline)', 'Hyoscine (injection)', 'Nifedipine (tocolytic)', 'Hydrocortisone (injection)');

-- 2. Rename brand-as-generic and non-INN labels.
UPDATE drug_master
SET generic_name = 'Pheniramine Maleate'
WHERE lower(generic_name) = lower('Avil (injection)');

UPDATE drug_master
SET generic_name = 'Etofylline + Theophylline'
WHERE lower(generic_name) = lower('Deriphyllin (injection)');

UPDATE drug_master
SET generic_name = 'Hyoscine Butylbromide'
WHERE lower(generic_name) = lower('Buscopan (injection)');

UPDATE drug_master
SET generic_name = 'Beclomethasone + Clotrimazole + Chloramphenicol + Lidocaine'
WHERE lower(generic_name) = lower('Candibiotic (ear)');

UPDATE drug_master
SET generic_name = 'Paradichlorobenzene + Benzocaine + Chlorbutol + Turpentine Oil'
WHERE lower(generic_name) = lower('Wax softener');

UPDATE drug_master
SET generic_name = 'Levonorgestrel + Ethinylestradiol',
    brand_names = ARRAY['Mala-N','Ovral']
WHERE lower(generic_name) = lower('Combined Oral Contraceptive');

UPDATE drug_master
SET generic_name = 'Aluminium Hydroxide + Magnesium Hydroxide + Simethicone'
WHERE lower(generic_name) = lower('Antacid (Aluminium + Magnesium)');

-- 3. Strip route / site parentheticals from generic_name.
UPDATE drug_master
SET generic_name = 'Diclofenac'
WHERE lower(generic_name) = lower('Diclofenac (topical)');

UPDATE drug_master
SET generic_name = 'Ciprofloxacin'
WHERE lower(generic_name) = lower('Ciprofloxacin (eye)');

UPDATE drug_master
SET generic_name = 'Tobramycin'
WHERE lower(generic_name) = lower('Tobramycin (eye)');

UPDATE drug_master
SET generic_name = 'Xylometazoline'
WHERE lower(generic_name) = lower('Xylometazoline (nasal)');

UPDATE drug_master
SET generic_name = 'Budesonide'
WHERE lower(generic_name) = lower('Budesonide (oral)');

UPDATE drug_master
SET generic_name = 'Fluticasone'
WHERE lower(generic_name) = lower('Fluticasone (inhaled)');

UPDATE drug_master
SET generic_name = 'Codeine'
WHERE lower(generic_name) = lower('Codeine (cough)');

UPDATE drug_master
SET generic_name = 'Oxymetazoline'
WHERE lower(generic_name) = lower('Oxymetazoline (nasal)');

UPDATE drug_master
SET generic_name = 'Fluticasone'
WHERE lower(generic_name) = lower('Fluticasone (nasal)');

UPDATE drug_master
SET generic_name = 'Mometasone'
WHERE lower(generic_name) = lower('Mometasone (nasal)');

UPDATE drug_master
SET generic_name = 'Azelastine'
WHERE lower(generic_name) = lower('Azelastine (nasal)');

UPDATE drug_master
SET generic_name = 'Fluticasone'
WHERE lower(generic_name) = lower('Fluticasone (topical)');

UPDATE drug_master
SET generic_name = 'Hydrocortisone'
WHERE lower(generic_name) = lower('Hydrocortisone (topical)');

UPDATE drug_master
SET generic_name = 'Tacrolimus'
WHERE lower(generic_name) = lower('Tacrolimus (topical)');

UPDATE drug_master
SET generic_name = 'Clindamycin'
WHERE lower(generic_name) = lower('Clindamycin (topical)');

UPDATE drug_master
SET generic_name = 'Ketoconazole'
WHERE lower(generic_name) = lower('Ketoconazole (topical)');

UPDATE drug_master
SET generic_name = 'Terbinafine'
WHERE lower(generic_name) = lower('Terbinafine (topical)');

UPDATE drug_master
SET generic_name = 'Ketoprofen'
WHERE lower(generic_name) = lower('Ketoprofen (topical)');

UPDATE drug_master
SET generic_name = 'Finasteride'
WHERE lower(generic_name) = lower('Finasteride (topical)');

UPDATE drug_master
SET generic_name = 'Moxifloxacin'
WHERE lower(generic_name) = lower('Moxifloxacin (eye)');

UPDATE drug_master
SET generic_name = 'Ofloxacin'
WHERE lower(generic_name) = lower('Ofloxacin (eye)');

UPDATE drug_master
SET generic_name = 'Gatifloxacin'
WHERE lower(generic_name) = lower('Gatifloxacin (eye)');

UPDATE drug_master
SET generic_name = 'Chloramphenicol'
WHERE lower(generic_name) = lower('Chloramphenicol (eye)');

UPDATE drug_master
SET generic_name = 'Sodium Hyaluronate'
WHERE lower(generic_name) = lower('Sodium Hyaluronate (eye)');

UPDATE drug_master
SET generic_name = 'Olopatadine'
WHERE lower(generic_name) = lower('Olopatadine (eye)');

UPDATE drug_master
SET generic_name = 'Ketorolac'
WHERE lower(generic_name) = lower('Ketorolac (eye)');

UPDATE drug_master
SET generic_name = 'Prednisolone'
WHERE lower(generic_name) = lower('Prednisolone (eye)');

UPDATE drug_master
SET generic_name = 'Atropine'
WHERE lower(generic_name) = lower('Atropine (eye)');

UPDATE drug_master
SET generic_name = 'Ofloxacin'
WHERE lower(generic_name) = lower('Ofloxacin (ear)');

UPDATE drug_master
SET generic_name = 'Ciprofloxacin'
WHERE lower(generic_name) = lower('Ciprofloxacin (ear)');

UPDATE drug_master
SET generic_name = 'Clotrimazole'
WHERE lower(generic_name) = lower('Clotrimazole (ear)');

UPDATE drug_master
SET generic_name = 'Benzocaine'
WHERE lower(generic_name) = lower('Benzocaine (ear)');

UPDATE drug_master
SET generic_name = 'Budesonide'
WHERE lower(generic_name) = lower('Budesonide (nasal)');

UPDATE drug_master
SET generic_name = 'Amiodarone'
WHERE lower(generic_name) = lower('Amiodarone (IV)');

UPDATE drug_master
SET generic_name = 'Potassium Chloride'
WHERE lower(generic_name) = lower('Potassium Chloride (IV)');

UPDATE drug_master
SET generic_name = 'Sodium Bicarbonate'
WHERE lower(generic_name) = lower('Sodium Bicarbonate (IV)');

UPDATE drug_master
SET generic_name = 'Diclofenac'
WHERE lower(generic_name) = lower('Diclofenac (injection)');

UPDATE drug_master
SET generic_name = 'Tramadol'
WHERE lower(generic_name) = lower('Tramadol (injection)');

UPDATE drug_master
SET generic_name = 'Ondansetron'
WHERE lower(generic_name) = lower('Ondansetron (injection)');

UPDATE drug_master
SET generic_name = 'Pantoprazole'
WHERE lower(generic_name) = lower('Pantoprazole (injection)');

UPDATE drug_master
SET generic_name = 'Methylprednisolone'
WHERE lower(generic_name) = lower('Methylprednisolone (injection)');

UPDATE drug_master
SET generic_name = 'Levonorgestrel'
WHERE lower(generic_name) = lower('Levonorgestrel (ECP)');

-- 4. Insert FDC + programme + missing-single rows.
INSERT INTO drug_master (generic_name, brand_names, strength, form, route_default)
SELECT * FROM (VALUES
  ('Aceclofenac + Paracetamol + Serratiopeptidase', ARRAY['Zerodol-SP','Hifenac-SP','Aceron-SP'], '100/325/15mg', 'tablet', 'oral'),
  ('Diclofenac + Paracetamol + Serratiopeptidase', ARRAY['Enzoflam','Diclogesic-SP'], '50/325/10mg', 'tablet', 'oral'),
  ('Aceclofenac + Serratiopeptidase', ARRAY['Zerodol-S','Hifenac-S'], '100/15mg', 'tablet', 'oral'),
  ('Diclofenac + Serratiopeptidase', ARRAY['Seradic','Emanzen-D'], '50/10mg', 'tablet', 'oral'),
  ('Etoricoxib + Thiocolchicoside', ARRAY['Etoshine-MR','Nucoxia-MR'], '60/4mg', 'tablet', 'oral'),
  ('Aceclofenac + Thiocolchicoside', ARRAY['Zerodol-TH','Hifenac-TH'], '100/4mg', 'tablet', 'oral'),
  ('Diclofenac + Tizanidine', ARRAY['Dynapar-MR','Diclofenac-T'], '50/2mg', 'tablet', 'oral'),
  ('Aceclofenac + Tizanidine', ARRAY['Zerodol-T','Hifenac-T'], '100/2mg', 'tablet', 'oral'),
  ('Trypsin + Chymotrypsin', ARRAY['Chymoral Forte','K-Tripsin'], '100000AU', 'tablet', 'oral'),
  ('Gabapentin + Nortriptyline', ARRAY['Gabapin-NT','Nortipan'], '400/10mg', 'tablet', 'oral'),
  ('Pregabalin + Nortriptyline', ARRAY['Pregalin-NT','Maxgalin-NT'], '75/10mg', 'tablet', 'oral'),
  ('Gabapentin + Methylcobalamin', ARRAY['Gabapin-ME','Nervijen-G'], '300/500mcg', 'tablet', 'oral'),
  ('Methylcobalamin + Alpha Lipoic Acid + Pyridoxine + Folic Acid', ARRAY['Nurokind-Plus','Methycobal-Plus'], '1500mcg', 'tablet', 'oral'),
  ('Ofloxacin + Ornidazole', ARRAY['Oflox-OZ','Zanocin-OZ','Oflomac-OZ'], '200/500mg', 'tablet', 'oral'),
  ('Levofloxacin + Ornidazole', ARRAY['Levoflox-OZ','Glevo-OZ'], '250/500mg', 'tablet', 'oral'),
  ('Norfloxacin + Tinidazole', ARRAY['Norflox-TZ','Norilet-TZ'], '400/600mg', 'tablet', 'oral'),
  ('Ciprofloxacin + Tinidazole', ARRAY['Cifran-TZ','Ciplox-TZ'], '500/600mg', 'tablet', 'oral'),
  ('Metronidazole + Norfloxacin', ARRAY['Nor-Metrogyl','Gramoneg-M'], '400/400mg', 'tablet', 'oral'),
  ('Ceftriaxone + Sulbactam', ARRAY['Monocef-SB','Xone-SB'], '1.5g', 'injection', 'IV'),
  ('Ceftriaxone + Tazobactam', ARRAY['Monocef-TZ','Oframax-TZ'], '1.125g', 'injection', 'IV'),
  ('Cefotaxime + Sulbactam', ARRAY['Taxim-S','Omnatax-S'], '1.5g', 'injection', 'IV'),
  ('Doxycycline + Lactobacillus', ARRAY['Doxt-SL','Microdox-LB'], '100mg', 'capsule', 'oral'),
  ('Isoniazid + Rifampicin + Pyrazinamide', ARRAY['Akurit-3','R-Cinex-Z'], '3FDC', 'tablet', 'oral'),
  ('Isoniazid + Rifampicin + Ethambutol', ARRAY['Akurit','Macox-ZH'], '3FDC', 'tablet', 'oral'),
  ('Rabeprazole + Levosulpiride', ARRAY['Razo-L','Rabicip-L','Veloz-L'], '20/75mg', 'capsule', 'oral'),
  ('Esomeprazole + Levosulpiride', ARRAY['Esoz-L','Sompraz-L'], '40/75mg', 'capsule', 'oral'),
  ('Pantoprazole + Levosulpiride', ARRAY['Pan-L','Pantocid-L'], '40/75mg', 'capsule', 'oral'),
  ('Pantoprazole + Itopride', ARRAY['Pan-IT','Pantop-IT'], '40/150mg', 'capsule', 'oral'),
  ('Rabeprazole + Itopride', ARRAY['Razo-IT','Rabicip-IT'], '20/150mg', 'capsule', 'oral'),
  ('Omeprazole + Cinitapride', ARRAY['Omez-CP','Cintapro-O'], '20/3mg', 'capsule', 'oral'),
  ('Pantoprazole + Cinitapride', ARRAY['Pan-CP','Cintapro-P'], '40/3mg', 'capsule', 'oral'),
  ('Dicyclomine + Mefenamic Acid', ARRAY['Meftal-Spas','Cyclopam-MF'], '10/250mg', 'tablet', 'oral'),
  ('Drotaverine + Mefenamic Acid', ARRAY['Drotin-M','Doverin-M'], '80/250mg', 'tablet', 'oral'),
  ('Sucralfate + Oxetacaine', ARRAY['Sucrafil-O','Mucaine Gel'], '1g/20mg', 'syrup', 'oral'),
  ('ORS + Zinc', ARRAY['Electral-Z','Walyte-Z'], '21g/20mg', 'sachet', 'oral'),
  ('Levosalbutamol + Ambroxol + Guaifenesin', ARRAY['Ascoril-LS','Ambrolite-S'], '1/30/50mg', 'syrup', 'oral'),
  ('Ambroxol + Levosalbutamol', ARRAY['Ambrodil-S','Kofarest-PD'], '30/1mg', 'syrup', 'oral'),
  ('Montelukast + Bambuterol', ARRAY['Montair-Plus','Telekast-B'], '10/10mg', 'tablet', 'oral'),
  ('Doxofylline + Montelukast', ARRAY['Doxolin-M','Doxofyl-M'], '400/10mg', 'tablet', 'oral'),
  ('Etofylline + Theophylline', ARRAY['Deriphyllin','Unicontin'], '77/23mg', 'tablet', 'oral'),
  ('Formoterol + Glycopyrronium + Budesonide', ARRAY['Glycohale-FB','Airz-FB'], '6/9/400mcg', 'inhaler', 'inhaled'),
  ('Indacaterol + Glycopyrronium', ARRAY['Ultibro','Indacaterol-Glyco'], '110/50mcg', 'inhaler', 'inhaled'),
  ('Umeclidinium + Vilanterol', ARRAY['Anoro Ellipta'], '62.5/25mcg', 'inhaler', 'inhaled'),
  ('Tiotropium + Formoterol', ARRAY['Duova','Tiova-F'], '18/12mcg', 'inhaler', 'inhaled'),
  ('Budesonide + Levosalbutamol', ARRAY['Budecort-LS','Derinide-LS'], '0.5/1.25mg', 'nebuliser', 'inhaled'),
  ('Ipratropium + Salbutamol', ARRAY['Duolin','Ipravent-S'], '500/2.5mg', 'nebuliser', 'inhaled'),
  ('Paracetamol + Phenylephrine + Cetirizine', ARRAY['Sinarest-AF','Wikoryl'], '325/10/5mg', 'tablet', 'oral'),
  ('Paracetamol + Phenylephrine + Chlorpheniramine', ARRAY['Sinarest','Alex-P','Wikoryl-Plus'], '500/10/2mg', 'tablet', 'oral'),
  ('Levocetirizine + Ambroxol', ARRAY['Levocet-A','Xyzal-A'], '5/60mg', 'tablet', 'oral'),
  ('Montelukast + Bilastine', ARRAY['Bilaxten-M','Bilazest-M'], '10/20mg', 'tablet', 'oral'),
  ('Montelukast + Rupatadine', ARRAY['Rupafin-M','Rupanex-M'], '10/10mg', 'tablet', 'oral'),
  ('Telmisartan + Chlorthalidone', ARRAY['Telma-CT','Tazloc-CT'], '40/12.5mg', 'tablet', 'oral'),
  ('Telmisartan + Metoprolol', ARRAY['Telma-Beta','Tazloc-MT'], '40/50mg', 'tablet', 'oral'),
  ('Telmisartan + Cilnidipine', ARRAY['Telma-LN','Cilacar-T'], '40/10mg', 'tablet', 'oral'),
  ('Telmisartan + Bisoprolol', ARRAY['Telma-B','Concor-T'], '40/5mg', 'tablet', 'oral'),
  ('Telmisartan + Amlodipine + Chlorthalidone', ARRAY['Telma-ACT','Tazloc-ACT'], '40/5/12.5mg', 'tablet', 'oral'),
  ('Telmisartan + Amlodipine + Hydrochlorothiazide', ARRAY['Telma-AMH','Tazloc-AMH'], '40/5/12.5mg', 'tablet', 'oral'),
  ('Olmesartan + Chlorthalidone', ARRAY['Olmesar-CH','Olmy-CH'], '20/12.5mg', 'tablet', 'oral'),
  ('Olmesartan + Hydrochlorothiazide', ARRAY['Olmesar-H','Olmy-H'], '20/12.5mg', 'tablet', 'oral'),
  ('Olmesartan + Amlodipine + Hydrochlorothiazide', ARRAY['Olmesar-AH','Olmy-AH'], '20/5/12.5mg', 'tablet', 'oral'),
  ('Losartan + Amlodipine', ARRAY['Repace-AM','Losacar-A'], '50/5mg', 'tablet', 'oral'),
  ('Metoprolol + Amlodipine', ARRAY['Met XL-AM','Prolomet-AM'], '50/5mg', 'tablet', 'oral'),
  ('Atenolol + Chlorthalidone', ARRAY['Tenoric','Atecard-C'], '50/12.5mg', 'tablet', 'oral'),
  ('Ramipril + Hydrochlorothiazide', ARRAY['Cardace-H','Ramcor-H'], '5/12.5mg', 'tablet', 'oral'),
  ('Enalapril + Hydrochlorothiazide', ARRAY['Envas-H','Enam-H'], '5/12.5mg', 'tablet', 'oral'),
  ('Nebivolol + Amlodipine', ARRAY['Nebistar-AM','Nodon-AM'], '5/5mg', 'tablet', 'oral'),
  ('Bisoprolol + Amlodipine', ARRAY['Concor-AM','Corbis-AM'], '5/5mg', 'tablet', 'oral'),
  ('Cilnidipine + Metoprolol', ARRAY['Cilacar-M','Cinod-M'], '10/50mg', 'tablet', 'oral'),
  ('Torsemide + Spironolactone', ARRAY['Dytor-Plus','Tide-Plus'], '10/25mg', 'tablet', 'oral'),
  ('Furosemide + Spironolactone', ARRAY['Lasilactone','Fruselac'], '20/50mg', 'tablet', 'oral'),
  ('Rosuvastatin + Fenofibrate', ARRAY['Rosuvas-F','Rozavel-F'], '10/160mg', 'tablet', 'oral'),
  ('Atorvastatin + Fenofibrate', ARRAY['Atorlip-F','Storvas-F'], '10/160mg', 'tablet', 'oral'),
  ('Aspirin + Atorvastatin', ARRAY['Ecosprin-AV','Atorva-ASP'], '75/10mg', 'tablet', 'oral'),
  ('Aspirin + Rosuvastatin', ARRAY['Rozustat-ASP','Rosuvas-ASP'], '75/10mg', 'tablet', 'oral'),
  ('Metformin + Gliclazide', ARRAY['Diamicron-M','Glizid-M'], '500/80mg', 'tablet', 'oral'),
  ('Metformin + Glipizide', ARRAY['Glytop-M','Glynase-MF'], '500/5mg', 'tablet', 'oral'),
  ('Metformin + Pioglitazone', ARRAY['Pioz-MF','Pioglit-MF'], '500/15mg', 'tablet', 'oral'),
  ('Metformin + Voglibose', ARRAY['Volibo-M','Volix-M'], '500/0.3mg', 'tablet', 'oral'),
  ('Metformin + Linagliptin', ARRAY['Trajenta-Duo','Ondero-M'], '500/2.5mg', 'tablet', 'oral'),
  ('Metformin + Saxagliptin', ARRAY['Kombiglyze','Onglyza-M'], '500/5mg', 'tablet', 'oral'),
  ('Metformin + Glimepiride + Pioglitazone', ARRAY['Glycomet-GP-Pio','Gemer-P'], '500/2/15mg', 'tablet', 'oral'),
  ('Metformin + Glimepiride + Voglibose', ARRAY['Glycomet-GP-V','Gemer-PV'], '500/2/0.2mg', 'tablet', 'oral'),
  ('Dapagliflozin + Sitagliptin', ARRAY['Oxra-S','Dapanorm-S'], '10/100mg', 'tablet', 'oral'),
  ('Dapagliflozin + Vildagliptin', ARRAY['Dapanorm-V','Jalra-D'], '10/100mg', 'tablet', 'oral'),
  ('Dapagliflozin + Linagliptin', ARRAY['Oxra-L','Dapanorm-L'], '10/5mg', 'tablet', 'oral'),
  ('Empagliflozin + Linagliptin', ARRAY['Glyxambi','Gibrus-L'], '10/5mg', 'tablet', 'oral'),
  ('Metformin + Dapagliflozin + Sitagliptin', ARRAY['Oxra-SM','Dapanorm-SM'], '500/10/100mg', 'tablet', 'oral'),
  ('Insulin Degludec + Insulin Aspart', ARRAY['Ryzodeg'], '100IU/ml', 'injection', 'SC'),
  ('Ferrous Ascorbate + Folic Acid', ARRAY['Orofer-XT','Fericip-XT','Richar-CR'], '100/1.5mg', 'tablet', 'oral'),
  ('Carbonyl Iron + Folic Acid + Zinc + Vitamin B12', ARRAY['Autrin','Fesovit'], '100/1.5/22.5/15mcg', 'capsule', 'oral'),
  ('Iron + Folic Acid + Vitamin B12', ARRAY['Fefol-Z','Livogen-Z'], '150/1.5/15mcg', 'tablet', 'oral'),
  ('Calcium Carbonate + Vitamin D3 + Magnesium + Zinc', ARRAY['Shelcal-M','Calcimax-P'], '500mg', 'tablet', 'oral'),
  ('Calcium + Vitamin D3 + Vitamin K2-7', ARRAY['Shelcal-K','Cipcal-K'], '500mg', 'tablet', 'oral'),
  ('Methylcobalamin + Pyridoxine + Folic Acid', ARRAY['Nurokind-LC','Methycobal-Plus'], '1500/3/1.5mg', 'tablet', 'oral'),
  ('Clobetasol + Salicylic Acid', ARRAY['Tenovate-S','Clonate-S'], '0.05%/3%', 'ointment', 'topical'),
  ('Benzoyl Peroxide + Clindamycin', ARRAY['Peroclin','Clinmiskin-Plus'], '2.5%/1%', 'gel', 'topical'),
  ('Adapalene + Benzoyl Peroxide', ARRAY['Epiduo','Deriva-BPO'], '0.1%/2.5%', 'gel', 'topical'),
  ('Ketoconazole + Zinc Pyrithione', ARRAY['Nizral-ZP','Keto-Z'], '2%/1%', 'shampoo', 'topical'),
  ('Ivermectin + Albendazole', ARRAY['Ivecop-A','Bandy-Plus'], '6/400mg', 'tablet', 'oral'),
  ('Moxifloxacin + Dexamethasone', ARRAY['Moxicip-D','Milflox-D'], '0.5%/0.1%', 'drops', 'other'),
  ('Brimonidine + Timolol', ARRAY['Alphagan-T','Brimolol'], '0.2%/0.5%', 'drops', 'other'),
  ('Dorzolamide + Timolol', ARRAY['Dorzo-T','Cosopt'], '2%/0.5%', 'drops', 'other'),
  ('Latanoprost + Timolol', ARRAY['Latoprost-T','Xalacom'], '0.005%/0.5%', 'drops', 'other'),
  ('Bimatoprost + Timolol', ARRAY['Lumigan-T','Careprost-T'], '0.03%/0.5%', 'drops', 'other'),
  ('Ofloxacin + Ornidazole', ARRAY['Oflox-OZ Ear','Zanocin-OZ Ear'], '0.3%/1%', 'drops', 'other'),
  ('Ofloxacin + Dexamethasone', ARRAY['Oflox-D Ear','Zanocin-D Ear'], '0.3%/0.1%', 'drops', 'other'),
  ('Ethinylestradiol + Cyproterone Acetate', ARRAY['Diane-35','Krimson-35','Ginette-35'], '0.035/2mg', 'tablet', 'oral'),
  ('Drospirenone + Ethinylestradiol', ARRAY['Yasmin','Yamini','Dronis-30'], '3/0.03mg', 'tablet', 'oral'),
  ('Ethinylestradiol + Desogestrel', ARRAY['Femilon','Novelon','Intimacy'], '0.03/0.15mg', 'tablet', 'oral'),
  ('Estradiol + Dydrogesterone', ARRAY['Femoston','Femoston-Conti'], '1/10mg', 'tablet', 'oral'),
  ('Tranexamic Acid + Mefenamic Acid', ARRAY['Pause-MF','Trapic-MF'], '500/250mg', 'tablet', 'oral'),
  ('Myo-inositol + D-chiro-inositol', ARRAY['Myo-Inositol','Ovacare'], '2000/50mg', 'sachet', 'oral'),
  ('Ferrous Ascorbate + Folic Acid + Calcium', ARRAY['Orofer-XT Plus','Fericip-XT Plus'], '100/1.5/250mg', 'tablet', 'oral'),
  ('Clofazimine', ARRAY['Lamprene','Hansepran'], '100mg', 'capsule', 'oral'),
  ('Cycloserine', ARRAY['Cycloserine','Coxerin'], '250mg', 'capsule', 'oral'),
  ('Bedaquiline', ARRAY['Sirturo','Bedaquiline'], '100mg', 'tablet', 'oral'),
  ('Delamanid', ARRAY['Deltyba'], '50mg', 'tablet', 'oral'),
  ('Pretomanid', ARRAY['Dovprela','Pretomanid'], '200mg', 'tablet', 'oral'),
  ('Ethionamide', ARRAY['Ethide','Trecator'], '250mg', 'tablet', 'oral'),
  ('Kanamycin', ARRAY['Kanamycin','Kannasyn'], '500mg', 'injection', 'IM'),
  ('Capreomycin', ARRAY['Capastat','Capreomycin'], '1g', 'injection', 'IM'),
  ('Para-aminosalicylic Acid', ARRAY['PAS','Paser'], '4g', 'sachet', 'oral'),
  ('Miltefosine', ARRAY['Impavido','Miltex'], '50mg', 'capsule', 'oral'),
  ('Amphotericin B (Liposomal)', ARRAY['Ambisome','Phosome','Fungisome'], '50mg', 'injection', 'IV'),
  ('Paromomycin', ARRAY['Humatin','Gabbroral'], '500mg', 'capsule', 'oral'),
  ('Sodium Stibogluconate', ARRAY['Pentostam','SSG'], '100mg/ml', 'injection', 'IM'),
  ('Artesunate', ARRAY['Falcigo','Larinate'], '60mg', 'injection', 'IV'),
  ('Sulfadoxine + Pyrimethamine', ARRAY['Fansidar','Malocide'], '500/25mg', 'tablet', 'oral'),
  ('Artesunate + Sulfadoxine-Pyrimethamine', ARRAY['Falcigo-SP','Larinate-SP'], '200/500/25mg', 'tablet', 'oral'),
  ('Snake Antivenom (Polyvalent)', ARRAY['ASVS','Snake Venom Antiserum'], '10ml', 'injection', 'IV'),
  ('Anti-Scorpion Venom Serum', ARRAY['SCORPION ANTIVENIN'], '1ml', 'injection', 'IV'),
  ('Rabies Immunoglobulin', ARRAY['Berirab','Equirab','Kamrab'], '300IU/ml', 'injection', 'IM'),
  ('Tetanus Immunoglobulin', ARRAY['Tigi','Tetagam','Ig-Tet'], '250IU', 'injection', 'IM'),
  ('Trimetazidine', ARRAY['Flavedon','Carvidon'], '35mg', 'tablet', 'oral'),
  ('Deflazacort', ARRAY['Defza','Defcort','Calcort'], '6mg', 'tablet', 'oral'),
  ('Nadifloxacin', ARRAY['Nadoxin','Nadibact'], '1%', 'cream', 'topical'),
  ('Nepafenac', ARRAY['Nevanac','Nepalact'], '0.1%', 'drops', 'other'),
  ('Bromfenac', ARRAY['Bromvue','Unibrom'], '0.09%', 'drops', 'other'),
  ('Alpha Lipoic Acid', ARRAY['R-Lipoic','Alphalip'], '300mg', 'capsule', 'oral'),
  ('Cinitapride', ARRAY['Cintapro','Kinpride'], '1mg', 'tablet', 'oral'),
  ('Oxetacaine', ARRAY['Mucaine','Oxetacaine'], '10mg', 'syrup', 'oral'),
  ('Bambuterol', ARRAY['Bambudil','Betaday'], '10mg', 'tablet', 'oral')
) AS seed(generic_name, brand_names, strength, form, route_default)
WHERE NOT EXISTS (
  SELECT 1 FROM drug_master dm
  WHERE lower(dm.generic_name) = lower(seed.generic_name)
    AND lower(coalesce(dm.form, '')) = lower(coalesce(seed.form, ''))
    AND lower(coalesce(dm.strength, '')) = lower(coalesce(seed.strength, ''))
);
