/**
 * Footer block for the prescription PDF (T3.15).
 *
 * Repeats on every page (mounted as `fixed` inside `<Page>` in the
 * root `PrescriptionDocument`). Carries:
 *   - signature line + typed-name fallback (Decision T3-D4: "no signature
 *     image → typed name as signature")
 *   - Clariva attribution
 *   - share-link short id (last 8 chars of prescription_id) so the
 *     patient can identify the artifact on a printed page
 *   - generated-at timestamp (doctor's clinic timezone)
 *   - page X / Y via @react-pdf/renderer's Text render-prop
 */

import * as React from 'react';
import { View, Text } from '@react-pdf/renderer';
import { styles } from './styles';
import type { PrescriptionPdfFooterData } from './types';

interface FooterProps {
  data: PrescriptionPdfFooterData;
}

export const Footer: React.FC<FooterProps> = ({ data }) => {
  const { doctorName, shortId, generatedAtLabel } = data;

  return (
    <View style={styles.footer} fixed>
      {/* Signature line (typed-name fallback per Decision T3-D4). The
          rendered line is empty — doctor types or signs over it on
          print. The typed name below is the legal "signed" anchor in
          the absence of an uploaded signature image (V1 limitation). */}
      <View style={styles.signatureLine}>
        <Text>{doctorName}</Text>
      </View>

      <View style={styles.footerRow}>
        <Text>
          Generated by Clariva on {generatedAtLabel} · Rx-ID …{shortId}
        </Text>
        <Text
          style={styles.pageNumber}
          render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages}`
          }
        />
      </View>
    </View>
  );
};
