/**
 * Footer block for the prescription PDF (T3.15 + clinic-branding-v1).
 *
 * Repeats on every page (`fixed`). `preprinted` hides the Halo footer so
 * the pad is not overwritten; a revision still prints the replaces-line.
 * Page counts are stamped after render (`page-numbers.ts`). A dynamic
 * `render` inside this footer drops the footer from the PDF.
 */

import * as React from 'react';
import { View, Text, Image } from '@react-pdf/renderer';
import { letterheadImageFitCss, letterheadTypePt } from '../../types/letterhead';
import { mmToPt, resolvePdfAccent, styles } from './styles';
import type { PrescriptionPdfFooterData, PrescriptionPdfLayout } from './types';

interface FooterProps {
  data: PrescriptionPdfFooterData;
  layout?: PrescriptionPdfLayout;
}

export const Footer: React.FC<FooterProps> = ({ data, layout }) => {
  const { shortId, generatedAtLabel, footerLine, hideHaloCredit, replacesLine } =
    data;
  const systemReplaces = replacesLine?.trim() || null;

  // Preprinted hides the Halo footer so the pad is not overwritten.
  // A revision still prints the system replaces-line (RXL-DL-11).
  if (layout?.preset === 'preprinted') {
    if (!systemReplaces) return null;
    return (
      <View style={styles.footer} fixed>
        <Text style={{ fontSize: 8, color: '#0F172A', marginBottom: 4 }}>
          {systemReplaces}
        </Text>
        <Text>Rx-ID …{shortId}</Text>
      </View>
    );
  }

  const banner = layout?.preset === 'banner' ? data.bannerSrc : null;
  const footerHeightMm = layout?.footerHeightMm ?? 20;
  const chrome = resolvePdfAccent(layout?.chromeColor ?? layout?.accentColor);

  const textFooter = (
    <View>
      {footerLine?.trim() ? (
        <Text
          style={{
            fontSize: letterheadTypePt('headerMeta', layout?.headerTextSize),
            color: chrome,
            marginBottom: 4,
          }}
        >
          {footerLine.trim()}
        </Text>
      ) : null}
      <Text style={{ fontSize: 7, color: '#64748B', marginBottom: 6 }}>
        Electronically generated — does not require signature
      </Text>
      {systemReplaces ? (
        <Text
          style={{ fontSize: 8, color: '#0F172A', marginBottom: 4 }}
        >
          {systemReplaces}
        </Text>
      ) : null}
      <View style={styles.footerRow}>
        <Text>
          {hideHaloCredit
            ? `Rx-ID …${shortId}`
            : `Generated by Halo Aid on ${generatedAtLabel} · Rx-ID …${shortId}`}
        </Text>
      </View>
    </View>
  );

  if (banner) {
    return (
      <View
        style={{ position: 'absolute', bottom: 0, left: 0, right: 0 }}
        fixed
      >
        <Image
          src={banner}
          style={{
            width: '100%',
            height: mmToPt(footerHeightMm),
            objectFit: letterheadImageFitCss(layout?.footerFit ?? 'stretch'),
          }}
        />
        <View style={{ paddingHorizontal: 36, paddingTop: 8, paddingBottom: 16 }}>
          {textFooter}
        </View>
      </View>
    );
  }

  return (
      <View style={styles.footer} fixed>
      {textFooter}
    </View>
  );
};
