/**
 * Transcript PDF composer (Plan 07 · Task 32 · Decision 1 sub + Decision 4
 * LOCKED).
 *
 * Pure rendering — NO database calls, NO I/O besides the pdfkit stream.
 * The service layer (`transcript-pdf-service.ts`) pulls the raw rows and
 * hands them here already-shaped; the composer's job is the deterministic
 * merge-by-timestamp → pdfkit-draw → footer-watermark cycle.
 *
 * Splitting "render" from "deliver" has two payoffs:
 *   1. The composer is unit-testable in isolation — feed it a synthesised
 *      message array + a mock pdfkit-like stream and assert the commands
 *      it issues (row shape, italic styling for system rows, page breaks
 *      on overflow, byte counter).
 *   2. If Notes #1 of the task ever flips the renderer from `pdfkit` to
 *      `@react-pdf/renderer` or `puppeteer`, only this file changes.
 *      The service layer stays on `{ output: NodeJS.WritableStream }` as
 *      its only contract.
 *
 * **Composition rules** (load-bearing; pinned by unit tests):
 *
 *   Letterhead block:
 *     [Clinic letterhead]
 *     Dr. {doctor_display_name}, {doctor_specialty}
 *     Consultation transcript
 *     Patient: {patient_display_name}
 *     Date:    {actual_ended_at formatted in doctor TZ}
 *     Modality: {modality}
 *     Session ID: {first-8-chars}...
 *
 *   Body (merge-by-timestamp of chat rows + voice/video transcript segments):
 *     kind='text'       → "{HH:MM}  {sender_label}: {body}"
 *     kind='attachment' → "{HH:MM}  {sender_label}: [attached: {mime} — {filename}]"
 *     kind='system'     → "{HH:MM}  [System: {body}]"  (italic + gray)
 *     voice segment     → "{HH:MM}  🎙 {speaker_label}: {text}"
 *
 *   Footer (every page):
 *     "Confidential — for personal medical use only."
 *     Separator.
 *     "This transcript was generated by Clariva on {now()}. For the
 *      authoritative audio recording, contact {clinic_name}."
 *     Separator.
 *     "Signed: Clariva Transcript Service (v1)"
 *
 * **Timestamp doctrine** — "HH:MM" in the doctor's timezone (matches the
 * in-chat system-message time formatter from Task 37). Seconds omitted
 * for readability.
 *
 * **Merge-order tie-breaker** — when two items share a timestamp, chat
 * messages sort BEFORE voice-transcript segments (arbitrary but
 * consistent; pinned).
 *
 * **Voice-transcript fallback** — when the voice transcription worker
 * hasn't finished yet (Plan 05 Task 25 dependency not ready), the
 * composer renders a placeholder section instead of blocking the
 * entire PDF. Text-only chat still renders.
 *
 * **Non-ASCII (Devanagari etc.)** — pdfkit's default Helvetica doesn't
 * cover Devanagari. Out of scope for v1 (Task 32 Notes #7); the composer
 * attempts rendering and lets pdfkit substitute glyphs where it can. A
 * future PR embeds `Noto Sans` via pdfkit's `registerFont` when clinic
 * usage shows real-world impact.
 *
 * @see docs/Development/Daily-plans/April 2026/19-04-2026/Tasks/task-32-transcript-pdf-export.md
 */

import PDFDocument from 'pdfkit';

// ============================================================================
// Public types
// ============================================================================

/** Message row shape (pre-flattened from `consultation_messages`). */
export type ChatMessageRow =
  | {
      kind:             'text';
      createdAtIso:     string;
      senderRole:       'doctor' | 'patient' | 'system';
      body:             string;
    }
  | {
      kind:             'attachment';
      createdAtIso:     string;
      senderRole:       'doctor' | 'patient' | 'system';
      body:             string | null;           // optional caption
      attachmentUrl:    string;
      attachmentMime:   string;
      attachmentBytes?: number;
    }
  | {
      kind:             'system';
      createdAtIso:     string;
      senderRole:       'system';
      body:             string;
      systemEvent?:     string;
    };

/**
 * Voice/video transcript segment (pre-flattened from one of the
 * `consultation_transcripts.transcript_json` shapes — the composer
 * doesn't care which provider produced it).
 *
 * `timestampIso` is absolute wall-clock time (derived upstream by adding
 * the segment's `start_sec` to `consultation_sessions.actual_started_at`).
 * The composer never does timezone math on this — it's already ISO UTC
 * and the composer's `formatTimeHHMM` helper converts to the doctor's
 * TZ for display.
 */
export interface VoiceTranscriptSegment {
  timestampIso: string;
  /** Pre-resolved speaker display name (e.g. "Dr. Sharma"). May be
   *  "Speaker" when diarization is unavailable (Whisper v1). */
  speakerLabel: string;
  text:         string;
}

/** Everything the composer needs about the enclosing session. */
export interface ComposeTranscriptContext {
  sessionId:        string;
  doctorDisplayName: string;
  doctorSpecialty?: string;
  practiceName?:    string;
  /** IANA tz (e.g. "Asia/Kolkata"). Fallback inside composer. */
  doctorTimezone?:  string;
  patientDisplayName: string;
  /** ISO of `consultation_sessions.actual_ended_at`. Drives the date
   *  in the letterhead. */
  consultEndedAtIso: string;
  /** "text" | "voice" | "video" — shown in the letterhead block. */
  modality:          string;
  /** When `true`, the voice transcript section renders a
   *  "Transcript not yet available — audio transcription is still
   *  processing" placeholder in place of spoken lines. Text-only chat
   *  still renders. */
  voiceTranscriptionPending: boolean;
}

export interface ComposeTranscriptInput {
  context:         ComposeTranscriptContext;
  messages:        ChatMessageRow[];
  voiceSegments:   VoiceTranscriptSegment[];
  output:          NodeJS.WritableStream;
  /** Generated-on timestamp for the footer. Defaults to `new Date()`. */
  generatedAt?:    Date;
}

export interface ComposeTranscriptResult {
  bytesWritten: number;
}

// ============================================================================
// Constants
// ============================================================================

const PAGE_MARGIN = 48;
const FOOTER_HEIGHT = 72;
const WATERMARK_TEXT = 'Confidential — for personal medical use only.';
const SIGNATURE_TEXT = 'Signed: Clariva Transcript Service (v1)';
const DEFAULT_TZ = 'Asia/Kolkata';

// ============================================================================
// Public: composeTranscriptPdfStream
// ============================================================================

/**
 * Render a consult transcript to a pdfkit stream. Returns the byte count
 * drained to `output` (measured via a tap on the write side; pdfkit
 * emits `data` events for every buffer so we count there).
 *
 * The caller owns `output` — the composer does NOT call `.end()` on it
 * directly (pdfkit's own `.end()` on the PDFDocument flushes and emits
 * the final `'end'` on the piped stream). This keeps the "upload via
 * PassThrough → Supabase Storage" wiring clean upstream.
 */
export async function composeTranscriptPdfStream(
  input: ComposeTranscriptInput,
): Promise<ComposeTranscriptResult> {
  const {
    context,
    messages,
    voiceSegments,
    output,
    generatedAt = new Date(),
  } = input;

  const tz = context.doctorTimezone?.trim() || DEFAULT_TZ;

  // pdfkit writes to the doc, the doc pipes to `output`. We tap the
  // write by replacing `output.write` with a counter wrapper — non-
  // invasive and avoids needing a PassThrough just for counting.
  let bytesWritten = 0;
  const originalWrite = output.write.bind(output) as (
    chunk: unknown,
    ...rest: unknown[]
  ) => boolean;
  (output as unknown as { write: typeof originalWrite }).write = ((
    chunk: unknown,
    ...rest: unknown[]
  ) => {
    if (Buffer.isBuffer(chunk)) bytesWritten += chunk.length;
    else if (typeof chunk === 'string') bytesWritten += Buffer.byteLength(chunk);
    return originalWrite(chunk, ...rest);
  }) as typeof originalWrite;

  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: PAGE_MARGIN, bottom: PAGE_MARGIN + FOOTER_HEIGHT, left: PAGE_MARGIN, right: PAGE_MARGIN },
    info: {
      Title:    `Consult transcript — ${truncateSessionId(context.sessionId)}`,
      Author:   'Clariva',
      Subject:  'Consultation transcript',
      Keywords: `consult, transcript, ${context.sessionId}`,
      CreationDate: generatedAt,
    },
    bufferPages: true,
    // Compression is deliberately OFF. Transcripts are small (<100KB
    // typical), so the bandwidth savings are trivial vs. the benefit:
    // an uncompressed PDF's content streams are greppable — support
    // can check what text landed in a delivered PDF without a parser,
    // and our unit tests can assert string presence in the raw bytes.
    // Decision captured in the composer's header comment.
    compress: false,
  });

  // Pipe to the tapped output. The returned promise resolves on 'end'
  // from the *output* side — not from pdfkit — so a slow consumer (e.g.
  // a network upload) flows naturally.
  const donePromise = new Promise<void>((resolve, reject) => {
    output.on('finish', resolve);
    output.on('end',    resolve);
    output.on('error',  reject);
  });

  doc.pipe(output as NodeJS.WritableStream);

  // ---- 1. Letterhead ----------------------------------------------------
  drawLetterhead(doc, context, tz);

  // ---- 2. Body ----------------------------------------------------------
  if (context.voiceTranscriptionPending && context.modality !== 'text') {
    drawTranscriptionPendingBanner(doc);
  }

  const merged = mergeByTimestamp(messages, voiceSegments);
  if (merged.length === 0) {
    doc
      .fontSize(10)
      .fillColor('#666')
      .font('Helvetica-Oblique')
      .text('(No messages recorded for this consult.)', { align: 'left' })
      .moveDown(0.5)
      .fillColor('#000')
      .font('Helvetica');
  } else {
    drawBody(doc, merged, context, tz);
  }

  // ---- 3. Footer on every page ------------------------------------------
  //
  // We use pdfkit's `bufferPages` mode to draw the footer post-body: the
  // alternative ("draw footer eagerly on pageAdded") recurses infinitely
  // because the footer writes below `page.margins.bottom`, which triggers
  // another pageAdded, which fires the listener again, and so on.
  //
  // `bufferedPageRange()` returns `{ start, count }` — we iterate every
  // already-rendered page, `switchToPage(i)`, and call drawFooter which
  // uses absolute x/y with `lineBreak: false` so pdfkit won't auto-flow.
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    drawFooter(doc, { practiceName: context.practiceName, generatedAt });
  }

  doc.end();

  await donePromise;
  return { bytesWritten };
}

// ============================================================================
// Merge-by-timestamp (pinned)
// ============================================================================

type MergedItem =
  | ({ source: 'chat' } & ChatMessageRow)
  | ({ source: 'voice' } & VoiceTranscriptSegment);

/**
 * Two-pointer merge of chat messages + voice segments into one
 * timestamp-ordered list. Chat-source ties beat voice-source ties
 * (stable + arbitrary but pinned). Exported for unit tests.
 */
export function mergeByTimestamp(
  messages: ChatMessageRow[],
  voiceSegments: VoiceTranscriptSegment[],
): MergedItem[] {
  const chatSorted = [...messages].sort(
    (a, b) => a.createdAtIso.localeCompare(b.createdAtIso),
  );
  const voiceSorted = [...voiceSegments].sort(
    (a, b) => a.timestampIso.localeCompare(b.timestampIso),
  );
  const out: MergedItem[] = [];
  let i = 0;
  let j = 0;
  while (i < chatSorted.length && j < voiceSorted.length) {
    const chatTs  = chatSorted[i].createdAtIso;
    const voiceTs = voiceSorted[j].timestampIso;
    // Tie-breaker: chat first (documented contract).
    if (chatTs <= voiceTs) {
      out.push({ source: 'chat', ...chatSorted[i++] });
    } else {
      out.push({ source: 'voice', ...voiceSorted[j++] });
    }
  }
  while (i < chatSorted.length) out.push({ source: 'chat', ...chatSorted[i++] });
  while (j < voiceSorted.length) out.push({ source: 'voice', ...voiceSorted[j++] });
  return out;
}

// ============================================================================
// Internals — drawing
// ============================================================================

type PdfKitDoc = InstanceType<typeof PDFDocument>;

function drawLetterhead(
  doc: PdfKitDoc,
  ctx: ComposeTranscriptContext,
  tz: string,
): void {
  const clinicLine = ctx.practiceName?.trim() || "Clariva Clinic";
  doc
    .font('Helvetica-Bold')
    .fontSize(16)
    .fillColor('#000')
    .text(clinicLine, { align: 'left' });

  doc
    .font('Helvetica')
    .fontSize(10)
    .fillColor('#444')
    .text(
      `Dr. ${ctx.doctorDisplayName}${
        ctx.doctorSpecialty ? `, ${ctx.doctorSpecialty}` : ''
      }`,
      { align: 'left' },
    );

  doc.moveDown(0.5);
  doc
    .font('Helvetica-Bold')
    .fontSize(13)
    .fillColor('#000')
    .text('Consultation transcript', { align: 'left' });
  doc.moveDown(0.2);

  doc
    .font('Helvetica')
    .fontSize(10)
    .fillColor('#000');
  const dateLabel = formatDateLabel(ctx.consultEndedAtIso, tz);
  doc.text(`Patient: ${ctx.patientDisplayName || '—'}`);
  doc.text(`Date:    ${dateLabel}`);
  doc.text(`Modality: ${ctx.modality}`);
  doc.text(`Session ID: ${truncateSessionId(ctx.sessionId)}...`);

  doc.moveDown(0.8);
  doc
    .strokeColor('#bbb')
    .lineWidth(0.5)
    .moveTo(doc.page.margins.left, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .stroke();
  doc.moveDown(0.5);
}

function drawTranscriptionPendingBanner(doc: PdfKitDoc): void {
  doc
    .font('Helvetica-Bold')
    .fontSize(10)
    .fillColor('#a60')
    .text('── Audio transcription pending ──', { align: 'center' })
    .moveDown(0.2)
    .font('Helvetica')
    .fillColor('#666')
    .text(
      'The spoken portion of this consult is still being transcribed. ' +
        'Please re-download in a few minutes for the complete transcript.',
      { align: 'center' },
    )
    .moveDown(0.8)
    .fillColor('#000');
}

function drawBody(
  doc: PdfKitDoc,
  merged: MergedItem[],
  ctx: ComposeTranscriptContext,
  tz: string,
): void {
  doc.font('Helvetica').fontSize(10).fillColor('#000');
  for (const item of merged) {
    drawRow(doc, item, ctx, tz);
    doc.moveDown(0.15);
  }
}

function drawRow(
  doc: PdfKitDoc,
  item: MergedItem,
  ctx: ComposeTranscriptContext,
  tz: string,
): void {
  if (item.source === 'voice') {
    const hhmm = formatTimeHHMM(item.timestampIso, tz);
    doc
      .font('Helvetica')
      .fillColor('#000')
      .text(`${hhmm}  🎙 ${item.speakerLabel}: ${item.text}`, { align: 'left' });
    return;
  }
  const hhmm = formatTimeHHMM(item.createdAtIso, tz);
  if (item.kind === 'system') {
    doc
      .font('Helvetica-Oblique')
      .fillColor('#555')
      .text(`${hhmm}  [System: ${item.body}]`, { align: 'left' })
      .font('Helvetica')
      .fillColor('#000');
    return;
  }
  const senderLabel = resolveChatSenderLabel(item.senderRole, ctx);
  if (item.kind === 'attachment') {
    const filename = extractFilename(item.attachmentUrl);
    const body =
      `${hhmm}  ${senderLabel}: [attached: ${item.attachmentMime} — ${filename}]` +
      (item.body ? ` — ${item.body}` : '');
    doc.font('Helvetica').fillColor('#000').text(body, { align: 'left' });
    return;
  }
  // kind === 'text'
  doc
    .font('Helvetica')
    .fillColor('#000')
    .text(`${hhmm}  ${senderLabel}: ${item.body}`, { align: 'left' });
}

function drawFooter(
  doc: PdfKitDoc,
  opts: { practiceName?: string; generatedAt: Date },
): void {
  const pageBottom = doc.page.height - doc.page.margins.bottom + 8;
  const leftX = doc.page.margins.left;
  const rightX = doc.page.width - doc.page.margins.right;

  doc
    .strokeColor('#bbb')
    .lineWidth(0.5)
    .moveTo(leftX, pageBottom - 4)
    .lineTo(rightX, pageBottom - 4)
    .stroke();

  const clinic = opts.practiceName?.trim() || 'your clinic';
  const genLabel = opts.generatedAt.toISOString();

  // `lineBreak: false` + explicit `height` keeps pdfkit from treating a
  // footer overrun as "time to paginate" — this is the fix for the
  // infinite-recursion bug we hit in the first cut where footer writes
  // kept triggering new pages.
  const footerTextOpts = {
    width:      rightX - leftX,
    align:      'center' as const,
    lineBreak:  false,
    height:     12,
  };

  doc
    .font('Helvetica')
    .fontSize(8)
    .fillColor('#777')
    .text(WATERMARK_TEXT, leftX, pageBottom, footerTextOpts)
    .text(
      `This transcript was generated by Clariva on ${genLabel}. For the authoritative audio recording, contact ${clinic}.`,
      leftX,
      pageBottom + 12,
      footerTextOpts,
    )
    .text(SIGNATURE_TEXT, leftX, pageBottom + 36, footerTextOpts);
}

// ============================================================================
// Internals — formatting
// ============================================================================

function formatTimeHHMM(iso: string, tz: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '--:--';
  try {
    return new Intl.DateTimeFormat('en-GB', {
      timeZone: tz,
      hour:    '2-digit',
      minute:  '2-digit',
      hour12:  false,
    }).format(d);
  } catch {
    return new Intl.DateTimeFormat('en-GB', {
      timeZone: DEFAULT_TZ,
      hour:    '2-digit',
      minute:  '2-digit',
      hour12:  false,
    }).format(d);
  }
}

function formatDateLabel(iso: string, tz: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '—';
  try {
    return new Intl.DateTimeFormat('en-GB', {
      timeZone: tz,
      day:   '2-digit',
      month: 'short',
      year:  'numeric',
    }).format(d);
  } catch {
    return new Intl.DateTimeFormat('en-GB', {
      timeZone: DEFAULT_TZ,
      day:   '2-digit',
      month: 'short',
      year:  'numeric',
    }).format(d);
  }
}

function truncateSessionId(sessionId: string): string {
  const trimmed = (sessionId ?? '').trim();
  if (trimmed.length <= 8) return trimmed;
  return trimmed.slice(0, 8);
}

function extractFilename(url: string): string {
  const trimmed = (url ?? '').trim();
  if (!trimmed) return 'file';
  const noQuery = trimmed.split('?')[0];
  const segments = noQuery.split('/');
  const last = segments[segments.length - 1] ?? '';
  return last || 'file';
}

function resolveChatSenderLabel(
  role: 'doctor' | 'patient' | 'system',
  ctx: ComposeTranscriptContext,
): string {
  switch (role) {
    case 'doctor': {
      const name = ctx.doctorDisplayName?.trim();
      return name ? `Dr. ${name}` : 'Doctor';
    }
    case 'patient':
      return 'Patient';
    case 'system':
      // System rows are rendered via the `[System: ...]` branch; this
      // label is a defensive fallback only.
      return 'System';
  }
}
