/**
 * rxl-26 — PDF footer replaces-line must survive letterhead + hideHaloCredit.
 */

import * as React from 'react';
import { Footer } from '../../../src/templates/prescription-pdf/Footer';
import type { PrescriptionPdfFooterData } from '../../../src/templates/prescription-pdf/types';

jest.mock('@react-pdf/renderer', () => ({
  View: ({ children }: { children?: React.ReactNode }) =>
    React.createElement('view', null, children),
  Text: ({ children }: { children?: React.ReactNode }) =>
    React.createElement('text', null, children),
  Image: () => React.createElement('image'),
}));

jest.mock('../../../src/templates/prescription-pdf/styles', () => ({
  mmToPt: (mm: number) => (mm * 72) / 25.4,
  resolvePdfAccent: () => '#111111',
  styles: {
    footer: {},
    footerRow: {},
    pageNumber: {},
  },
}));

const REPLACES =
  'Revised 6:40 PM, 9 Sep 2026 — replaces the slip issued 10:15 AM. Version 2.';

function footerData(
  overrides: Partial<PrescriptionPdfFooterData> = {}
): PrescriptionPdfFooterData {
  return {
    doctorName: 'Dr. Test',
    shortId: 'abcd1234',
    generatedAtLabel: 'Sep 9, 2026 · 6:40 PM IST',
    ...overrides,
  };
}

function collectText(node: React.ReactNode): string[] {
  const out: string[] = [];
  const walk = (n: React.ReactNode): void => {
    if (n == null || typeof n === 'boolean') return;
    if (typeof n === 'string' || typeof n === 'number') {
      out.push(String(n));
      return;
    }
    if (Array.isArray(n)) {
      n.forEach(walk);
      return;
    }
    if (!React.isValidElement(n)) return;
    walk((n.props as { children?: React.ReactNode }).children);
  };
  walk(node);
  return out;
}

describe('Footer replaces-line (rxl-26)', () => {
  it('omits the line on Version 1', () => {
    const texts = collectText(Footer({ data: footerData() }));
    expect(texts.join(' ')).not.toMatch(/Revised|Version 2/);
    expect(texts.join(' ')).toContain('Rx-ID …abcd1234');
  });

  it('renders the pharmacist copy beside the short id', () => {
    const texts = collectText(
      Footer({ data: footerData({ replacesLine: REPLACES }) })
    );
    expect(texts).toContain(REPLACES);
    expect(texts.join(' ')).toContain('Rx-ID …abcd1234');
  });

  it('survives hideHaloCredit and a custom footerLine', () => {
    const texts = collectText(
      Footer({
        data: footerData({
          replacesLine: REPLACES,
          hideHaloCredit: true,
          footerLine: 'Reg. No. 123 · Custom clinic footer',
        }),
      })
    );
    expect(texts).toContain(REPLACES);
    expect(texts).toContain('Reg. No. 123 · Custom clinic footer');
    expect(texts.join(' ')).not.toMatch(/Generated by Halo Aid/);
    expect(texts.join(' ')).toContain('Rx-ID …abcd1234');
  });

  it('prints the replaces-line on a preprinted pad', () => {
    const texts = collectText(
      Footer({
        data: footerData({ replacesLine: REPLACES }),
        layout: {
          preset: 'preprinted',
          pageSize: 'a4',
          accentColor: '#000000',
          preprintMarginTopMm: 40,
          preprintMarginBottomMm: 30,
        },
      })
    );
    expect(texts).toContain(REPLACES);
    expect(texts.join(' ')).not.toMatch(/Generated by Halo Aid/);
  });

  it('stays hidden on an unrevised preprinted pad', () => {
    const result = Footer({
      data: footerData(),
      layout: {
        preset: 'preprinted',
        pageSize: 'a4',
        accentColor: '#000000',
        preprintMarginTopMm: 40,
        preprintMarginBottomMm: 30,
      },
    });
    expect(result).toBeNull();
  });
});
