import { render, screen, within } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import {
  LetterheadPagePreview,
  overflowingPreviewPages,
  packPreviewBlocks,
  PAGE_PACK_SLACK_PX,
  previewMeasureHeightsReady,
  previewPackBudgets,
  previewPageBodiesReady,
  RX_COL_WIDTHS,
  shiftOverflowingPreviewPages,
} from "@/components/settings/LetterheadPagePreview";

class ResizeObserverMock {
  observe() {}
  unobserve() {}
  disconnect() {}
}

vi.stubGlobal("ResizeObserver", ResizeObserverMock);

const model = {
  doctorName: "Dr. Test",
  qualifications: "MBBS",
  specialty: "GP",
  clinicName: "Halo Clinic",
  clinicAddress: "1 Main St",
  logoUrl: null,
  preset: "classic" as const,
  pageSize: "a4" as const,
  accentColor: "#1D4ED8",
  preprintMarginTopMm: 40,
  preprintMarginBottomMm: 30,
};

describe("packPreviewBlocks", () => {
  it("starts a new sheet when the current one is full", () => {
    expect(packPreviewBlocks([80, 80, 80, 80], 150, 200)).toEqual([
      [0],
      [1, 2],
      [3],
    ]);
    expect(packPreviewBlocks([40, 40], 200, 200)).toEqual([[0, 1]]);
    expect(packPreviewBlocks([90, 90, 90], 80, 80)).toEqual([[0], [1], [2]]);
  });

  it("reserves slack so a medicine plus notes is not packed against the footer", () => {
    const { page1, later } = previewPackBudgets(1000, 200, 80);
    expect(page1).toBe(1000 - 200 - 80 - PAGE_PACK_SLACK_PX);
    expect(later).toBe(1000 - 80 - PAGE_PACK_SLACK_PX);
    expect(
      packPreviewBlocks([70, 70], page1, later),
    ).toEqual([[0, 1]]);
    expect(
      packPreviewBlocks([700, 40], page1, later),
    ).toEqual([[0], [1]]);
  });
});

describe("shiftOverflowingPreviewPages", () => {
  it("moves the last block of a clipped sheet onto the next page", () => {
    expect(shiftOverflowingPreviewPages([[0, 1, 2], [3]], [true, false])).toEqual(
      [[0, 1], [2, 3]],
    );
  });

  it("leaves a single oversized block on its sheet", () => {
    expect(shiftOverflowingPreviewPages([[0]], [true])).toEqual([[0]]);
  });
});

describe("preview layout ready-checks", () => {
  it("does not treat unmeasured heights as ready", () => {
    expect(previewMeasureHeightsReady([], 2)).toBe(false);
    expect(previewMeasureHeightsReady([40, 0], 2)).toBe(false);
    expect(previewMeasureHeightsReady([40, 36], 2)).toBe(true);
    expect(previewMeasureHeightsReady([], 0)).toBe(true);
  });

  it("does not treat a 0-height page body as laid out or overflowing", () => {
    const missing = [null, { clientHeight: 80, scrollHeight: 80 }];
    expect(previewPageBodiesReady(missing, 2)).toBe(false);
    expect(overflowingPreviewPages(missing, 2)).toEqual([false, false]);

    const unpainted = [{ clientHeight: 0, scrollHeight: 240 }];
    expect(previewPageBodiesReady(unpainted, 1)).toBe(false);
    expect(overflowingPreviewPages(unpainted, 1)).toEqual([false]);

    const clipped = [
      { clientHeight: 200, scrollHeight: 260 },
      { clientHeight: 200, scrollHeight: 200 },
    ];
    expect(previewPageBodiesReady(clipped, 2)).toBe(true);
    expect(overflowingPreviewPages(clipped, 2)).toEqual([true, false]);
  });
});

describe("LetterheadPagePreview", () => {
  it("renders a full A4 sample prescription, not a header strip only", () => {
    render(<LetterheadPagePreview model={model} variant="dialog" />);

    expect(
      screen.getByRole("article", { name: /a4 prescription preview/i }),
    ).toBeInTheDocument();
    expect(screen.getByText("Halo Clinic")).toBeInTheDocument();
    expect(screen.queryByText("Dr. Test")).not.toBeInTheDocument();
    expect(screen.getByText("Sample patient")).toBeInTheDocument();
    expect(screen.getByText("Paracetamol 500 mg")).toBeInTheDocument();
    expect(
      screen.getByText(/electronically generated — does not require signature/i),
    ).toBeInTheDocument();
    expect(screen.getByText(/generated by halo aid/i)).toBeInTheDocument();
  });

  it("keeps the thumb variant to a small paper size", () => {
    const { container } = render(
      <LetterheadPagePreview model={model} variant="thumb" />,
    );
    const frame = container.firstElementChild as HTMLElement;
    expect(Number.parseFloat(frame.style.width)).toBeLessThan(180);
    expect(Number.parseFloat(frame.style.height)).toBeLessThan(260);
  });

  it("renders banner header and footer photos when provided", () => {
    render(
      <LetterheadPagePreview
        model={{
          ...model,
          preset: "banner",
          headerUrl: "https://example.test/header.png",
          footerUrl: "https://example.test/footer.png",
          headerHeightMm: 30,
          footerHeightMm: 18,
        }}
      />,
    );

    const images = screen.getAllByRole("presentation");
    const page = screen.getByRole("article", {
      name: /a4 prescription preview/i,
    });
    expect(Number.parseFloat(page.style.paddingTop)).toBeGreaterThan(0);
    expect(images.some((img) => img.getAttribute("src")?.includes("header"))).toBe(
      true,
    );
    expect(images.some((img) => img.getAttribute("src")?.includes("footer"))).toBe(
      true,
    );
    expect(screen.getByText("Sample patient")).toBeInTheDocument();
  });

  it("applies fit tokens to header, footer, and background photos", () => {
    render(
      <LetterheadPagePreview
        model={{
          ...model,
          preset: "banner",
          headerUrl: "https://example.test/header.png",
          footerUrl: "https://example.test/footer.png",
          headerFit: "fit",
          footerFit: "fill",
          backgroundFit: "stretch",
          backgroundPreset: "upload",
          backgroundUrl: "https://example.test/bg.png",
        }}
      />,
    );

    const images = screen.getAllByRole("presentation");
    const header = images.find((img) =>
      img.getAttribute("src")?.includes("header"),
    );
    const footer = images.find((img) =>
      img.getAttribute("src")?.includes("footer"),
    );
    const background = images.find((img) =>
      img.getAttribute("src")?.includes("bg.png"),
    );
    expect(header).toHaveClass("object-contain");
    expect(footer).toHaveClass("object-cover");
    expect(background).toHaveClass("object-fill");
  });

  it("paints header identity and patient copy with their colours", () => {
    render(
      <LetterheadPagePreview
        model={{
          ...model,
          clinicName: "Dr Abhishek Sahil",
          chromeColor: "#000000",
          patientColor: "#B45309",
          accentColor: "#1D4ED8",
        }}
      />,
    );

    expect(screen.getByText("Dr Abhishek Sahil")).toHaveStyle({ color: "#000000" });
    expect(screen.getByText("Sample patient")).toHaveStyle({ color: "#B45309" });
    expect(screen.getByText("Chief complaint")).toHaveStyle({ color: "#1D4ED8" });
  });

  it("paints a faint paper page background under the prescription", () => {
    render(
      <LetterheadPagePreview
        model={{
          ...model,
          backgroundPreset: "paper",
          backgroundOpacity: 15,
        }}
      />,
    );

    const bg = screen
      .getAllByRole("presentation")
      .find((img) => img.getAttribute("src")?.includes("bg-paper"));
    expect(bg).toBeTruthy();
    expect(bg).toHaveStyle({ opacity: "0.15" });
  });

  it("keeps 0% background strength as fully transparent", () => {
    render(
      <LetterheadPagePreview
        model={{
          ...model,
          backgroundPreset: "paper",
          backgroundOpacity: 0,
        }}
      />,
    );

    const bg = screen
      .getAllByRole("presentation")
      .find((img) => img.getAttribute("src")?.includes("bg-paper"));
    expect(bg).toHaveStyle({ opacity: "0" });
  });

  it("keeps open-letter date on the right, not inlined after the name", () => {
    render(<LetterheadPagePreview model={model} />);
    expect(screen.getByText("Sample patient")).toBeInTheDocument();
    expect(screen.getByText("24 Aug 2026")).toBeInTheDocument();
    expect(screen.queryByText(/Sample patient\s*·/)).not.toBeInTheDocument();
  });

  it("inlines name, age, and date when the patient preset is compact", () => {
    const { container } = render(
      <LetterheadPagePreview
        model={{ ...model, patientIdentityPreset: "compact" }}
      />,
    );
    expect(container.textContent).toMatch(
      /Sample patient\s*·\s*50 y · M\s*·\s*24 Aug 2026/,
    );
  });

  it("renders hospital chart cells when the patient preset is grid", () => {
    render(
      <LetterheadPagePreview
        model={{ ...model, patientIdentityPreset: "grid" }}
      />,
    );

    expect(screen.getByText(/MRN/)).toBeInTheDocument();
    expect(screen.getByText(/Name/)).toBeInTheDocument();
    expect(screen.getByText(/Address/)).toBeInTheDocument();
  });

  it("shows one letterhead title on classic, not two doctor names", () => {
    render(
      <LetterheadPagePreview
        model={{
          ...model,
          doctorName: "Dr. Zurb",
          clinicName: "Dr Abhishek Sahil",
        }}
      />,
    );

    expect(screen.getByText("Dr Abhishek Sahil")).toBeInTheDocument();
    expect(screen.queryByText("Dr. Zurb")).not.toBeInTheDocument();
  });

  it("prints investigations as a two-column tick list with a note", () => {
    render(
      <LetterheadPagePreview
        model={{
          ...model,
          rx: {
            patientName: "Jaspreet Sandhu",
            investigations:
              "CBC, HbA1c, fasting glucose. Bring home BP diary to the next visit.",
            medicines: [],
          },
        }}
      />,
    );

    expect(screen.getByText("CBC")).toBeInTheDocument();
    expect(screen.getByText("HbA1c")).toBeInTheDocument();
    expect(screen.getByText("fasting glucose")).toBeInTheDocument();
    expect(
      screen.getByText("Bring home BP diary to the next visit."),
    ).toBeInTheDocument();
    expect(
      screen.queryByText(/CBC, HbA1c, fasting glucose/),
    ).not.toBeInTheDocument();
    const invStart = screen.getByText("Investigations").closest("[data-inv-start]");
    expect(invStart?.textContent).toContain("CBC");
  });

  it("prints package members as nested ticks under the package name", () => {
    render(
      <LetterheadPagePreview
        model={{
          ...model,
          rx: {
            patientName: "Neha Kulkarni",
            investigations:
              "Thyroid profile; ECG; CBC: Haemoglobin, Albumin, ANA",
            medicines: [],
          },
        }}
      />,
    );

    expect(screen.getByText("Thyroid profile")).toBeInTheDocument();
    expect(screen.getByText("ECG")).toBeInTheDocument();
    expect(screen.getByText("CBC")).toBeInTheDocument();
    expect(screen.getByText("Haemoglobin")).toBeInTheDocument();
    expect(screen.getByText("Albumin")).toBeInTheDocument();
    expect(screen.getByText("ANA")).toBeInTheDocument();
    expect(
      screen.queryByText(/CBC: Haemoglobin/),
    ).not.toBeInTheDocument();
  });

  it("shows food and notes as a line under the medicine row", () => {
    render(
      <LetterheadPagePreview
        model={{
          ...model,
          rx: {
            patientName: "Harpreet Gill",
            medicines: [
              {
                name: "Salbutamol inhaler 100 mcg",
                dose: "2 puffs (100 mcg)",
                route: "Inhaled",
                frequency: "As needed",
                duration: "14 days",
                instructions:
                  "After food — 2 puffs when wheezy. Shake well.",
              },
            ],
          },
        }}
      />,
    );

    expect(screen.getByText("Salbutamol inhaler 100 mcg")).toBeInTheDocument();
    expect(screen.queryByText("Instructions")).not.toBeInTheDocument();
    expect(
      screen.getByText("> After food — 2 puffs when wheezy. Shake well."),
    ).toBeInTheDocument();
  });

  it("locks the split Rx header and body tables to the same column widths", () => {
    const { container } = render(
      <LetterheadPagePreview
        model={{
          ...model,
          rx: {
            patientName: "Sneha Kulkarni",
            medicines: [
              {
                name: "Naproxen 250 mg",
                dose: "1 tab (250 mg)",
                route: "Oral",
                frequency: "Twice daily",
                duration: "3 days",
                instructions: "After food — Take at onset of headache.",
              },
            ],
          },
        }}
      />,
    );

    const tables = [...container.querySelectorAll("table")].filter((table) =>
      table.querySelector("colgroup"),
    );
    expect(tables.length).toBeGreaterThanOrEqual(2);
    for (const table of tables) {
      expect(table.classList.contains("table-fixed")).toBe(true);
      const widths = [...table.querySelectorAll("col")].map(
        (col) => (col as HTMLElement).style.width,
      );
      expect(widths).toEqual([...RX_COL_WIDTHS]);
    }
  });

  it("keeps the Rx heading with the column header, then lists every medicine", () => {
    render(
      <LetterheadPagePreview
        model={{
          ...model,
          rx: {
            patientName: "Sneha Kulkarni",
            medicines: [
              {
                name: "Gel antacid",
                dose: "2 spoons",
                route: "Oral",
                frequency: "",
                duration: "",
                instructions: "After food",
              },
              {
                name: "Naproxen 250 mg",
                dose: "1 tab (250 mg)",
                route: "Oral",
                frequency: "Twice daily",
                duration: "3 days",
              },
              {
                name: "Dicyclomine",
                dose: "",
                route: "",
                frequency: "As needed",
                duration: "",
              },
              {
                name: "Diclofenac",
                dose: "",
                route: "",
                frequency: "As needed",
                duration: "",
              },
            ],
          },
        }}
      />,
    );

    const start = screen.getByText("Rx").closest("[data-rx-start]");
    expect(start).toBeTruthy();
    expect(start?.textContent).toMatch(/Medicine/);
    expect(start?.querySelector("thead")).toBeTruthy();
    expect(start?.textContent).not.toMatch(/Gel antacid/);
    expect(screen.getByText("Gel antacid")).toBeInTheDocument();
    expect(screen.getByText("Naproxen 250 mg")).toBeInTheDocument();
    expect(screen.getByText("Dicyclomine")).toBeInTheDocument();
    expect(screen.getByText("Diclofenac")).toBeInTheDocument();
  });

  it("renders the live visit instead of the settings sample", () => {
    render(
      <LetterheadPagePreview
        model={{
          ...model,
          rx: {
            patientName: "Harpreet Gill",
            cc: "cough",
            medicines: [],
          },
        }}
      />,
    );
    expect(screen.getByText("Harpreet Gill")).toBeInTheDocument();
    expect(screen.getByText("cough")).toBeInTheDocument();
    expect(screen.getByText(/no medicines prescribed/i)).toBeInTheDocument();
    expect(screen.queryByText("Sample patient")).not.toBeInTheDocument();
  });

  it("makes large body labels bigger than medium", () => {
    const { rerender } = render(<LetterheadPagePreview model={model} />);
    const medium = Number.parseFloat(
      screen.getByText("Chief complaint").style.fontSize,
    );
    rerender(
      <LetterheadPagePreview model={{ ...model, bodyTextSize: "large" }} />,
    );
    expect(
      Number.parseFloat(screen.getByText("Chief complaint").style.fontSize),
    ).toBeGreaterThan(medium);
  });

  it("hides letterhead chrome for the preprinted preset", () => {
    render(
      <LetterheadPagePreview
        model={{ ...model, preset: "preprinted", pageSize: "a5" }}
      />,
    );

    expect(
      screen.getByRole("article", { name: /a5 prescription preview/i }),
    ).toBeInTheDocument();
    expect(screen.getByText(/your printed letterhead/i)).toBeInTheDocument();
    expect(
      screen.queryByText(/electronically generated/i),
    ).not.toBeInTheDocument();
  });

  it("renders body sections in the same order as the printed PDF", () => {
    render(
      <LetterheadPagePreview
        model={{
          ...model,
          rx: {
            patientName: "Sneha Kulkarni",
            allergies: "Penicillin (severe — rash)",
            cc: "Headache",
            hopi: "Throbbing for 2 days",
            vitals: "BP 124/80 · HR 72",
            examinationFindings: "No focal deficit",
            socialHistory: "Non-smoker",
            diagnosis: "Migraine without aura",
            investigations: "CBC",
            advice: "Dark quiet room",
            followUp: "in 2 weeks",
            referral: "Neurology if not better",
            customSubsections: [
              {
                title: "Travel history",
                body: "Visited Kerala",
                children: [{ title: "Prophylaxis", body: "Doxycycline" }],
              },
            ],
            assessmentCustomSections: [
              { title: "Risk notes", body: "No red flags", children: [] },
            ],
            planCustomSections: [
              { title: "Physio", body: "Neck stretches", children: [] },
            ],
            medicines: [],
          },
        }}
      />,
    );

    const stack = screen.getByTestId("letterhead-preview-stack");
    const headings = within(stack)
      .getAllByRole("heading")
      .map((el) => el.textContent?.trim());
    expect(headings).toEqual([
      "Allergies",
      "Chief complaint",
      "History of present illness",
      "Vitals",
      "Examination",
      "Social history",
      "Travel history",
      "Prophylaxis",
      "Provisional diagnosis",
      "Risk notes",
      "Investigations",
      "Rx",
      "Advice",
      "Follow-up",
      "Referral",
      "Physio",
    ]);
  });
});
