"use client";

/**
 * AllergyClashBanner (EHR Sub-batch C / T4.18).
 *
 * Red banner that appears above the medicines section when ≥1 entered
 * medicine matches a documented patient allergy. Mounted by
 * `<PrescriptionForm>` and fed:
 *   - `medicines` — the form's draft rows mapped to the matcher's
 *                    `MatchableMedicine` shape (snake_case subset).
 *   - `medicineInstanceIds` — parallel array of stable per-row ids
 *                              generated by the form on add. A
 *                              remove-then-re-add produces a fresh id,
 *                              so any prior ack does NOT carry over
 *                              (per Done-when: "acknowledgements are
 *                              per-instance, not per-medicine-name").
 *   - `allergies` — the patient's active allergy rows (already
 *                    server-filtered by the chart service).
 *   - `drugMasterIndex` — Map of every drug_master row the doctor
 *                          has selected via T2.8 autocomplete in this
 *                          form session. Free-text-only medicines
 *                          have no entry → matcher degrades to
 *                          free-text candidates only (V1 brand-match
 *                          gap, documented in `tasks-subbatch-C-safety.md`).
 *   - acknowledgement primitives from `useAcknowledgements()` so the
 *     "Acknowledge and continue" button clears every currently-shown
 *     match in one state update.
 *
 * Decision T4-D1 LOCKED: this is a SOFT warning. The banner does not
 * disable Send and does not block any other action — it just informs.
 *
 * Decision §23 LOCKED but DEFERRED to C.4: this banner is silent —
 * no telemetry events are emitted from C.1. The pre-send aggregator
 * (T4.21) is the surface that knows the outcome and is the right
 * place to emit `{ doctor_id, rx_id, warning_kinds, outcome }`.
 *
 * @see frontend/lib/ehr/match-allergens.ts
 * @see frontend/lib/ehr/use-acknowledgements.ts
 */

import { useMemo } from "react";
import {
  matchAllergens,
  type AllergyMatch,
  type MatchableMedicine,
} from "@/lib/ehr/match-allergens";
import type { PatientAllergy } from "@/types/patient-chart";
import type { DrugMasterRow } from "@/types/drug-master";

interface AllergyClashBannerProps {
  medicines: ReadonlyArray<MatchableMedicine>;
  /** Parallel to `medicines` — `medicineInstanceIds[i]` is the stable
   *  row identity for `medicines[i]`. The banner combines this with
   *  `match.allergyId` to compute the ack key. */
  medicineInstanceIds: ReadonlyArray<string>;
  allergies: ReadonlyArray<PatientAllergy>;
  drugMasterIndex: ReadonlyMap<string, DrugMasterRow>;
  /** From `useAcknowledgements()` in the parent form. */
  isAcked: (key: string) => boolean;
  /** Acks a batch of keys in one state update — wired to
   *  `ackMany` so the "Acknowledge and continue" click never
   *  produces a flicker between two render passes. */
  onAcknowledge: (keys: ReadonlyArray<string>) => void;
}

/** Build the per-(medicine-instance, allergy) ack key. Exported so
 *  the form can re-derive keys when it needs to (e.g. clearing acks
 *  for rows that were removed). */
export function ackKeyForAllergyMatch(
  medicineInstanceId: string,
  allergyId: string,
): string {
  return `allergy:${medicineInstanceId}:${allergyId}`;
}

const SEVERITY_LABEL: Record<PatientAllergy["severity"], string> = {
  mild: "mild",
  moderate: "moderate",
  severe: "severe",
  unknown: "severity unknown",
};

export default function AllergyClashBanner({
  medicines,
  medicineInstanceIds,
  allergies,
  drugMasterIndex,
  isAcked,
  onAcknowledge,
}: AllergyClashBannerProps) {
  // Recompute matches whenever any input identity changes. The
  // matcher is pure + cheap (O(M × A × C)) so we don't bother with
  // deeper memoization — keystroke-rate updates on a draft Rx have
  // bounded fan-out (≤10 medicines × ≤10 allergies × ≤4 candidates).
  const matches = useMemo<AllergyMatch[]>(
    () => matchAllergens(medicines, allergies, drugMasterIndex),
    [medicines, allergies, drugMasterIndex],
  );

  // Filter to UNacknowledged matches. Two reasons we re-derive here
  // (vs filtering inside the matcher):
  //   1. The matcher must stay pure / ack-agnostic so T4.21's
  //      aggregator can read the full match set independently.
  //   2. The "Acknowledge and continue" click should clear EVERY
  //      currently-shown match — we need the displayed list as the
  //      source of truth for that batch.
  const unacked = useMemo<AllergyMatch[]>(() => {
    if (matches.length === 0) return matches;
    return matches.filter((m) => {
      const instanceId = medicineInstanceIds[m.medicineIndex];
      // If the parallel array got out of sync (defensive — should
      // not happen given form-side invariants), fall back to a
      // synthetic key so the match still surfaces. Prevents a stale
      // ack from silently swallowing a real warning.
      const key = instanceId
        ? ackKeyForAllergyMatch(instanceId, m.allergyId)
        : `allergy:fallback-${m.medicineIndex}:${m.allergyId}`;
      return !isAcked(key);
    });
  }, [matches, medicineInstanceIds, isAcked]);

  if (unacked.length === 0) return null;

  // De-dupe by allergyId for display: a single allergen matching
  // multiple medicines should still tell the doctor about each
  // medicine, but the allergen description (severity / reaction)
  // is rendered once per allergen.
  const groupedByAllergy = new Map<
    string,
    { allergyId: string; allergen: string; severity: string; reaction: string | null; medicines: string[] }
  >();
  for (const m of unacked) {
    const existing = groupedByAllergy.get(m.allergyId);
    if (existing) {
      if (m.medicineName && !existing.medicines.includes(m.medicineName)) {
        existing.medicines.push(m.medicineName);
      }
    } else {
      groupedByAllergy.set(m.allergyId, {
        allergyId: m.allergyId,
        allergen: m.allergenMatched,
        severity: SEVERITY_LABEL[m.severity],
        reaction: m.reaction,
        medicines: m.medicineName ? [m.medicineName] : [],
      });
    }
  }
  const groups = Array.from(groupedByAllergy.values());

  const handleAcknowledge = () => {
    const keys: string[] = [];
    for (const m of unacked) {
      const instanceId = medicineInstanceIds[m.medicineIndex];
      if (!instanceId) continue;
      keys.push(ackKeyForAllergyMatch(instanceId, m.allergyId));
    }
    onAcknowledge(keys);
  };

  return (
    <div
      role="alert"
      aria-live="polite"
      className="rounded-md border border-red-300 bg-red-50 p-3 text-red-900"
      data-testid="allergy-clash-banner"
    >
      <div className="flex items-start gap-2">
        <span className="mt-0.5 text-base leading-none" aria-hidden="true">
          ⚠️
        </span>
        <div className="flex-1 space-y-2">
          <p className="text-sm font-semibold">
            Allergy alert
            <span className="ml-2 text-xs font-normal text-red-700">
              {unacked.length} {unacked.length === 1 ? "match" : "matches"}
            </span>
          </p>
          <ul className="space-y-2 text-sm">
            {groups.map((g) => (
              <li key={g.allergyId} className="leading-snug">
                <p>
                  <span className="font-medium">{g.allergen}</span>
                  <span className="text-xs text-red-700">
                    {" "}
                    ({g.severity}
                    {g.reaction ? ` — ${g.reaction}` : ""})
                  </span>
                </p>
                {g.medicines.length > 0 && (
                  <p className="text-xs text-red-800">
                    Prescribed: {g.medicines.join(", ")}
                  </p>
                )}
              </li>
            ))}
          </ul>
          <div className="flex flex-wrap items-center gap-2 pt-1">
            <button
              type="button"
              onClick={handleAcknowledge}
              className="rounded-md border border-red-300 bg-white px-3 py-1.5 text-xs font-medium text-red-900 hover:bg-red-100 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-1"
            >
              Acknowledge and continue
            </button>
            <span className="text-xs text-red-700">
              Send is never blocked — review and proceed with clinical
              judgement.
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
