/**
 * Content-sanity test for migration 163 (full ICD-11 MMS import).
 *
 * assessment-tab · asmt-06 (Wave 6). This file is GENERATED by
 * `backend/scripts/generate-diagnosis-catalog-seed.js` from the WHO MMS
 * Simple Tabulation export; the assertions guard its shape + provenance, not
 * the generator internals.
 */

import { describe, expect, it } from '@jest/globals';
import { readFileSync } from 'fs';
import { resolve } from 'path';

const MIGRATION_PATH = resolve(
  __dirname,
  '../../../migrations/163_diagnosis_catalog_full_mms_import.sql',
);

describe('163_diagnosis_catalog_full_mms_import.sql', () => {
  const sql = readFileSync(MIGRATION_PATH, 'utf8');

  describe('provenance + generation', () => {
    it('is marked generated and cites the WHO MMS source + release + licence', () => {
      expect(sql).toMatch(/GENERATED FILE/);
      expect(sql).toMatch(/generate-diagnosis-catalog-seed\.js/);
      expect(sql).toMatch(/icdcdn\.who\.int/);
      expect(sql).toMatch(/2026-01/);
      expect(sql).toMatch(/CC BY-ND/);
      expect(sql).toMatch(/ICD-11/);
      expect(sql).toMatch(/MMS/);
    });
  });

  describe('seed body', () => {
    it('inserts into diagnosis_catalog in idempotent, code-guarded chunks', () => {
      expect(sql).toMatch(/INSERT INTO diagnosis_catalog \(code, title, synonyms, chapter\)/);
      expect(sql).toMatch(
        /WHERE NOT EXISTS \(\s*SELECT 1 FROM diagnosis_catalog d WHERE lower\(d\.code\) = lower\(v\.code\)/,
      );
    });

    it('imports the full catalog (thousands of codeable categories)', () => {
      const rowCount = (sql.match(/::text\[\]/g) || []).length;
      expect(rowCount).toBeGreaterThan(10000);
    });

    it('seeds canonical WHO titles for well-known codes', () => {
      expect(sql).toMatch(/\('BA00', 'Essential hypertension'/);
      expect(sql).toMatch(/\('5A11', 'Type 2 diabetes mellitus'/);
      expect(sql).toMatch(/\('CA23', 'Asthma'/);
      expect(sql).toMatch(/\('DD70', 'Crohn disease'/);
    });

    it('includes more specific child codes (e.g. 6D80.0)', () => {
      expect(sql).toMatch(/\('6D80\.0',/);
    });
  });

  describe('excluded chapters (not diagnoses)', () => {
    it('documents dropping Chapter X (extension) and Chapter V (functioning)', () => {
      expect(sql).toMatch(/Chapter X/);
      expect(sql).toMatch(/Chapter V/);
    });

    it('does not seed extension codes or functioning-assessment codes', () => {
      // XS8H is an extension code; VD00 is a WHODAS functioning code.
      expect(sql).not.toMatch(/\('XS8H'/);
      expect(sql).not.toMatch(/\('VD00'/);
    });
  });

  describe('PHI + RLS discipline (ASMT-D8)', () => {
    it('documents the import as NON-PHI', () => {
      expect(sql).toMatch(/NON-?PHI|PHI: NONE/i);
    });

    it('does NOT touch prescriptions RLS or table', () => {
      expect(sql).not.toMatch(/ALTER TABLE\s+prescriptions/i);
      expect(sql).not.toMatch(/\bON\s+prescriptions\b/i);
    });

    it('defines no schema — the table/indexes/RLS live in migration 162', () => {
      expect(sql).not.toMatch(/CREATE TABLE/i);
      expect(sql).not.toMatch(/ENABLE ROW LEVEL SECURITY/i);
    });
  });
});
